/* Copyright 2012 Google Inc. All Rights Reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

(function(){var a=void 0,f=!0,g=null,i=!1,j=window,k=document;function l(b,c){return b.toJSON=c}
var m="requestId",q="extend",r="addResponseListener",s="match",t="setAttribute",u="attachEvent",v="documentElement",w="toJSON",x="split",y="location",z="isArray",A="push",B="Request",C="indexOf",D="domain",E="addEventListener",F="param",G="length",H="prototype",I="clientWidth",J="document",K="body",L="call",M="clientHeight",N="toLowerCase",O="",aa=" from ",ba="#",P="&",ca="*",da=",height=",ea=",left=",fa=",status=1,location=1,resizable=yes,menubar=no,toolbar=no,titlebar=no,channelmode=no,directories=no,fullscreen=no",ga=
",top=",ha=".",ia="10.1",ja="10.5.6",Q="2.0",R="3.0",ka="4.0",la="4.7",S="6.0",T="7.0",ma="8.0",U="=",V="?",na="Android",oa="Failed to add iframe onload event.",pa="Ingore message from unrecognized domain: ",qa="Invalid JSON-RPC notification: no 'params.requestId' field found.",ra="Invalid JSON-RPC object: 'jsonrpc' field should be '2.0'.",sa="Invalid JSON-RPC object: no 'id' or 'method' field found.",ta="Invalid JSON-RPC object: not a JSON object.",ua="Invalid JSON-RPC response: invalid 'id' field.",
va="MSIE",wa="Method not found",xa="Opera Mini",ya="Opera Mobi",za="Parameter %%param%% cannot be an empty array.",W="Parameter %%param%% cannot be empty.",Aa="Parameter %%param%% cannot be null.",Ba="Parameter %%param%% is not a function.",Ca="Parameter %%param%% is not an array.",Da="Query request is not supported in popup mode.",Ea="Received message: ",Fa="Register handler for postMessage failed.",Ga="Send message: ",Ha="Unrecognized event type: ",Ia="Unrecognized rpc received: ",Ja="[object Array]",
Ka="[object Function]",X="_",La="about:blank",Ma="account",Na="accountchooser-iframe",Oa="accounts",Pa="callback",Qa="callbacks.",Ra="config",Sa="form",Ta="function",Ua="handler",Va="hidden",Y="id",Wa="iframe",Xa="input",Ya="load",Za="message",$a="name",ab="object",bb="oneTimeCallbacks.",cb="onload",db="onmessage",eb="parentClass",fb="popin-box",gb="position: absolute; width: 1px; height: 1px; left: -9999px;",hb="post",ib="query",jb="query_",kb="requestId",lb="select",mb="serviceName",nb="src",ob=
"store",pb="style",qb="targetWindow",rb="type",sb="update",tb="value",ub="version",vb="width=",Z;j.accountchooser=j.accountchooser||{};j.cds=j.accountchooser;j.accountchooser.util=j.accountchooser.util||{};j.accountchooser.util.log=function(b){try{j.console&&j.console.log&&j.console.log(b)}catch(c){}};j.accountchooser.util.uuidCounter_=(new Date).getTime();j.accountchooser.util.generateUuid=function(b){return b&&b.uuid?b.uuid:++j.accountchooser.util.uuidCounter_};
j.accountchooser.util.createForm_=function(b,c,d){if(!b)throw"The targetUrl cannot be null.";var e=j[J].createElement(Sa);e.method=hb;e.action=b;if(c)for(var h in c)b=j[J].createElement(Xa),b[t](rb,Va),b[t]($a,h),c[h]===g||c[h]===a?b[t](tb,O):b[t](tb,c[h]),e.appendChild(b);d&&(e.target=d);j[J][K].appendChild(e);return e};j.accountchooser.util.postTo=function(b,c,d){b=j.accountchooser.util.createForm_(b,c,d);b.submit();j[J][K].removeChild(b)};
j.accountchooser.util.parseUrlParams=function(b){var c={};b=b.slice(b[C](V)+1)[x](P);for(var d=0;d<b[G];d++){var e=b[d][x](U);c[e[0]]=2==e[G]?decodeURIComponent(e[1]):a}return c};j.accountchooser.util.formRedirect=function(b,c){var d=b.substring(0,b[C](V)),e=j.accountchooser.util.parseUrlParams(b);j.accountchooser.util.postTo(d,e,c)};j.accountchooser.util.isBrowserSupported=function(){var b=999;-1!=navigator.appVersion[C](va)&&(b=parseFloat(navigator.appVersion[x](va)[1]));return 7<b};
j.accountchooser.util.makeUrl=function(b,c){var d=[],e;for(e in c)d[A](c[e]?e+U+c[e]:e);return b+V+d.join(P)};j.accountchooser.util.AccountPropertyKey={EMAIL:"email",DISPLAY_NAME:"displayName",PHOTO_URL:"photoUrl",PROVIDER_ID:"providerId"};
j.accountchooser.util.sanitizeAccount=function(b,c){var d={},e=j.accountchooser.util.AccountPropertyKey,h;for(h in b)switch(h){case e.EMAIL:case e.DISPLAY_NAME:case e.PHOTO_URL:case e.PROVIDER_ID:d[h]=b[h];break;default:if(!c)throw'Unrecognized key "'+h+'" for account';}return d};j.accountchooser.util.sanitizeAccounts=function(b){for(var c=[],d=0,e=b[G];d<e;d++){var h=j.accountchooser.util.sanitizeAccount(b[d]);c[A](h)}return c};
j.accountchooser.util.isArray=function(b){return"undefined"!==typeof jQuery?jQuery[z](b):Object[H].toString[L](b)===Ja};j.accountchooser.util.isFunction=function(b){return"undefined"!==typeof jQuery?jQuery.isFunction(b):Object[H].toString[L](b)===Ka};j.accountchooser.util.indexOf=function(b,c){if(c){if("undefined"!==typeof jQuery)return jQuery.inArray(b,c);if(c[C])return c[C](b);for(var d=c[G],e=0;e<d;e++)if(e in c&&c[e]===b)return e}return-1};
j.accountchooser.util.windowWidth=function(b){if("undefined"!==typeof jQuery)return jQuery(b).width();var c=0;b.innerWidth?c=b.innerWidth:b[J]&&b[J][v]&&b[J][v][I]?c=b[J][v][I]:b[J]&&(b[J][K]&&b[J][K][I])&&(c=b[J][K][I]);return c};j.accountchooser.util.windowHeight=function(b){if("undefined"!==typeof jQuery)return jQuery(b).height();var c=0;b.innerHeight?c=b.innerHeight:b[J]&&b[J][v]&&b[J][v][M]?c=b[J][v][M]:b[J]&&(b[J][K]&&b[J][K][M])&&(c=b[J][K][M]);return c};
j.accountchooser.util.trim=function(b){return"undefined"!==typeof jQuery?jQuery.trim(b):b==g?O:String[H].trim?String[H].trim[L](b):b.replace(/^[\s\xa0]+/,O).replace(/[\s\xa0]+$/,O)};
j.accountchooser.util.extend=function(b,c,d){if(3>arguments[G])return c||{};if("undefined"!==typeof jQuery){var e=Array[H].slice[L](arguments,b?0:1);return jQuery[q].apply(jQuery,e)}if(typeof c!==ab||c==g)c={};for(var e=2,h=arguments[G];e<h;e++){var n=arguments[e];if(n!=g)for(var p in n)n[p]===a||c===n[p]||(b&&typeof n[p]==ab?(j.accountchooser.util[z](n[p])&&!j.accountchooser.util[z](c[p])&&(c[p]=[]),c[p]=j.accountchooser.util[q](f,c[p],n[p])):c[p]=n[p])}return c};j.accountchooser.param={};
j.accountchooser[F].notNull=function(b,c){(b===a||b===g)&&j.accountchooser[F].throwError_(Aa,c)};j.accountchooser[F].notEmpty=function(b,c){b||j.accountchooser[F].throwError_(W,c)};j.accountchooser[F].notEmptyArray=function(b,c){b||j.accountchooser[F].throwError_(W,c);j.accountchooser.util[z](b)||j.accountchooser[F].throwError_(Ca,c);b[G]||j.accountchooser[F].throwError_(za,c)};
j.accountchooser[F].notEmptyFunction=function(b,c){b||j.accountchooser[F].throwError_(W,c);j.accountchooser.util.isFunction(b)||j.accountchooser[F].throwError_(Ba,c)};j.accountchooser[F].throwError_=function(b,c){try{console&&console.trace&&console.trace()}catch(d){}throw b.replace(/\%\%param\%\%/g,c?" '"+c+"'":O);};Function[H].inheritsFrom=function(b){j.accountchooser[F].notEmptyFunction(b,eb);this.prototype=new b;this[H].constructor=this;this[H].parentClass=b[H]};
j.accountchooser.util.DEFAULT_POPUP_NAME="OpenIdPopup";j.accountchooser.util.showPopup=function(b,c,d,e){var h=(j.accountchooser.util.windowHeight(j)-c)/2,n=(j.accountchooser.util.windowWidth(j)-b)/2;e=e||j.accountchooser.util.DEFAULT_POPUP_NAME;if(b=j.open(d||La,e,vb+b+da+c+ea+(0<n?n:0)+ga+(0<h?h:0)+fa))!k.getElementById(fb)&&j.accountchooser.util.showDarkScreen&&j.accountchooser.util.showDarkScreen(b),j.accountchooser.util.popup_=b,j.accountchooser.util.popupName_=e,b.focus();return b};
j.accountchooser.util.REGEX_MSIE_UA_=/MSIE ([\d.]+).*Windows NT ([\d.]+)/;j.accountchooser.util.REGEX_FIREFOX_UA_=/Firefox\/([\d.]+)/;j.accountchooser.util.REGEX_OPERA_UA_=/Opera[ \/]([\d.]+)(.*Version\/([\d.]+))?/;j.accountchooser.util.REGEX_CHROME_UA_=/Chrome\/([\d.]+)/;j.accountchooser.util.REGEX_SAFARI_UA_=/((Windows NT ([\d.]+))|(Mac OS X ([\d_]+))).*Version\/([\d.]+).*Safari/;j.accountchooser.util.REGEX_ANDROID_UA_=/Android ([\d.]+).*Safari/;j.accountchooser.util.REGEX_MOBILE_SAFARI_UA_=/OS ([\d_]+) like Mac OS X.*Mobile.*Safari/;
j.accountchooser.util.REGEX_KONQUEROR_UA_=/Konqueror\/([\d.]+)/;j.accountchooser.util.REGEX_MOBILE_MSIE_UA_=/MSIE ([\d.]+).*Windows Phone OS ([\d.]+)/;j.accountchooser.util.Version=function(b,c){j.accountchooser[F].notEmpty(b,ub);this.version_=b;this.components_=b[x](c||ha);for(var d=0;d<this.components_[G];++d)this.components_[d]=parseInt(this.components_[d])};
j.accountchooser.util.Version[H].compare=function(b){b instanceof j.accountchooser.util.Version||(b=new j.accountchooser.util.Version(b));for(var c=Math.max(this.components_[G],b.components_[G]),d=0;d<c;++d){var e=this.components_[d],h=b.components_[d];if(e!==a&&h!==a&&e!==h)return e-h;if(e===a)return-1;if(h===a)return 1}return 0};j.accountchooser.util.Version[H].ge=function(b){return 0<=this.compare(b)};
j.accountchooser.util.isSNISupported=function(b){var c=b||j.navigator&&j.navigator.userAgent,d;if(c){if(d=c[s](j.accountchooser.util.REGEX_OPERA_UA_))return b=new j.accountchooser.util.Version(d[3]||d[1]),0<=c[C](xa)?i:0<=c[C](ya)?0<=c[C](na)&&b.ge(ia):b.ge(ma);if(d=c[s](j.accountchooser.util.REGEX_FIREFOX_UA_))return b=new j.accountchooser.util.Version(d[1]),b.ge(Q);if(d=c[s](j.accountchooser.util.REGEX_CHROME_UA_))return b=new j.accountchooser.util.Version(d[1]),b.ge(S);if(d=c[s](j.accountchooser.util.REGEX_SAFARI_UA_))return b=
new j.accountchooser.util.Version(d[6]),c=d[3]&&new j.accountchooser.util.Version(d[3]),d=d[5]&&new j.accountchooser.util.Version(d[5],X),(!(!c||!c.ge(S))||!(!d||!d.ge(ja)))&&b.ge(R);if(d=c[s](j.accountchooser.util.REGEX_ANDROID_UA_))return b=new j.accountchooser.util.Version(d[1]),b.ge(R);if(d=c[s](j.accountchooser.util.REGEX_MOBILE_SAFARI_UA_))return(new j.accountchooser.util.Version(d[1],X)).ge(ka);if(d=c[s](j.accountchooser.util.REGEX_KONQUEROR_UA_))return b=new j.accountchooser.util.Version(d[1]),
b.ge(la);if(d=c[s](j.accountchooser.util.REGEX_MOBILE_MSIE_UA_))return b=new j.accountchooser.util.Version(d[1]),c=new j.accountchooser.util.Version(d[2]),b.ge(T)&&c.ge(T);if(d=c[s](j.accountchooser.util.REGEX_MSIE_UA_))return b=new j.accountchooser.util.Version(d[1]),c=new j.accountchooser.util.Version(d[2]),b.ge(T)&&c.ge(S)}return i};j.accountchooser.util.SNI_NOT_SUPPORT_ERROR={error:"SNI is not supported."};
j.accountchooser.util.checkSNISupported=function(b){if(!j.accountchooser.util.isSNISupported(b))throw j.accountchooser.util.SNI_NOT_SUPPORT_ERROR;};j.accountchooser.rpc=j.accountchooser.rpc||{};j.accountchooser.rpc.RpcObject=function(){};j.accountchooser.rpc.RpcObject[H].setTimestamp=function(b){this.timestamp_=b||(new Date).getTime()};l(j.accountchooser.rpc.RpcObject[H],function(){var b={jsonrpc:Q};this.timestamp_!=g&&(b.timestamp=this.timestamp_);return b});
j.accountchooser.rpc.RpcObject[H].toString=function(){return JSON.stringify(this[w]())};j.accountchooser.rpc.AbstractRequest=function(b,c){this.method_=b;this.params_=c};j.accountchooser.rpc.AbstractRequest.inheritsFrom(j.accountchooser.rpc.RpcObject);Z=j.accountchooser.rpc.AbstractRequest[H];Z.setMethod=function(b){this.method_=b};Z.getMethod=function(){return this.method_};Z.setParameters=function(b){this.params_=b};Z.getParameters=function(){return this.params_};
l(Z,function(){var b=j.accountchooser.rpc.RpcObject[H][w][L](this);this.method_!=g&&(b.method=this.method_);this.params_!=g&&(b.params=this.params_);return b});j.accountchooser.rpc.Notification=function(b,c){this.method_=b;this.params_=c};j.accountchooser.rpc.Notification.inheritsFrom(j.accountchooser.rpc.AbstractRequest);j.accountchooser.rpc.Request=function(b,c,d){this.method_=b;this.params_=c;this.id_=d};j.accountchooser.rpc[B].inheritsFrom(j.accountchooser.rpc.AbstractRequest);
j.accountchooser.rpc[B][H].setId=function(b){this.id_=b};j.accountchooser.rpc[B][H].getId=function(){return this.id_};l(j.accountchooser.rpc[B][H],function(){var b=j.accountchooser.rpc.AbstractRequest[H][w][L](this);this.id_!=g&&(b.id=this.id_);return b});j.accountchooser.rpc.Response=function(b,c,d){j.accountchooser[F].notEmpty(b,Y);this.id_=b;this.result_=c;this.error_=d};j.accountchooser.rpc.Response.inheritsFrom(j.accountchooser.rpc.RpcObject);Z=j.accountchooser.rpc.Response[H];Z.getResult=function(){return this.result_};
Z.setResult=function(b){this.result_=b};Z.getError=function(){return this.error_};Z.setError=function(b){this.error_=b};Z.setId=function(b){this.id_=b};Z.getId=function(){return this.id_};l(Z,function(){var b=j.accountchooser.rpc.RpcObject[H][w][L](this);b.id=this.id_;this.result_!=g?b.result=this.result_:this.error_!=g&&(b.error=this.error_);return b});j.accountchooser.rpc.DEFAULT_CDS_DOMAIN="https://www.accountchooser.com";j.accountchooser.rpc.DEFAULT_CDS_IFRAME_PATH="/iframe.html";
j.accountchooser.rpc.DEFAULT_CDS_POPUP_PATH="/popup.html";j.accountchooser.rpc.DEFAULT_CDS_REDIRECT_PATH="/redirect.html";j.accountchooser.rpc.DEFAULT_POPUP_WIDTH=520;j.accountchooser.rpc.DEFAULT_POPUP_HEIGHT=550;j.accountchooser.rpc.EMPTY_RESPONSE_CALLBACK="empty";j.accountchooser.rpc.IDP_TIMEOUT=3E3;j.accountchooser.rpc.RPC_TIMEOUT=3E5;
j.accountchooser.rpc.RequestAckNotification=function(b){j.accountchooser[F].notEmpty(b,kb);this.method_=j.accountchooser.rpc.RequestAckNotification.METHOD;this.params_={requestId:b}};j.accountchooser.rpc.RequestAckNotification.inheritsFrom(j.accountchooser.rpc.Notification);j.accountchooser.rpc.RequestAckNotification.METHOD="requestAckNotification";j.accountchooser.rpc.RequestAckNotification[H].setRequestId=function(b){this.params_.requestId=b};
j.accountchooser.rpc.RequestAckNotification[H].getRequestId=function(){return this.params_[m]};j.accountchooser.rpc.CdsReadyNotification=function(){this.method_=j.accountchooser.rpc.CdsReadyNotification.METHOD};j.accountchooser.rpc.CdsReadyNotification.inheritsFrom(j.accountchooser.rpc.Notification);j.accountchooser.rpc.CdsReadyNotification.METHOD="cdsReadyNotification";j.accountchooser.rpc.ClientReadyNotification=function(){this.method_=j.accountchooser.rpc.ClientReadyNotification.METHOD};j.accountchooser.rpc.ClientReadyNotification.inheritsFrom(j.accountchooser.rpc.Notification);
j.accountchooser.rpc.ClientReadyNotification.METHOD="clientReadyNotification";j.accountchooser.rpc.EmptyResponseNotification=function(){this.method_=j.accountchooser.rpc.EmptyResponseNotification.METHOD};j.accountchooser.rpc.EmptyResponseNotification.inheritsFrom(j.accountchooser.rpc.Notification);j.accountchooser.rpc.EmptyResponseNotification.METHOD="emptyResponseNotification";
j.accountchooser.rpc.StoreRequest=function(b,c,d){j.accountchooser[F].notEmpty(b,Y);j.accountchooser[F].notEmptyArray(c,Oa);c&&(c=j.accountchooser.util.sanitizeAccounts(c));this.method_=j.accountchooser.rpc.StoreRequest.METHOD;this.params_={accounts:c,clientConfig:d};this.id_=b};j.accountchooser.rpc.StoreRequest.inheritsFrom(j.accountchooser.rpc[B]);j.accountchooser.rpc.StoreRequest.METHOD=ob;
j.accountchooser.rpc.SelectRequest=function(b,c,d){j.accountchooser[F].notEmpty(b,Y);c&&(c=j.accountchooser.util.sanitizeAccounts(c));this.method_=j.accountchooser.rpc.SelectRequest.METHOD;this.params_={localAccounts:c,clientConfig:d};this.id_=b};j.accountchooser.rpc.SelectRequest.inheritsFrom(j.accountchooser.rpc[B]);j.accountchooser.rpc.SelectRequest.METHOD=lb;
j.accountchooser.rpc.UpdateRequest=function(b,c,d){j.accountchooser[F].notEmpty(b,Y);j.accountchooser[F].notEmpty(c,Ma);c&&(c=j.accountchooser.util.sanitizeAccount(c));this.method_=j.accountchooser.rpc.UpdateRequest.METHOD;this.params_={account:c,clientConfig:d};this.id_=b};j.accountchooser.rpc.UpdateRequest.inheritsFrom(j.accountchooser.rpc[B]);j.accountchooser.rpc.UpdateRequest.METHOD=sb;
j.accountchooser.rpc.ManageRequest=function(b,c){j.accountchooser[F].notEmpty(b,Y);this.method_=j.accountchooser.rpc.ManageRequest.METHOD;this.params_={clientConfig:c};this.id_=b};j.accountchooser.rpc.ManageRequest.inheritsFrom(j.accountchooser.rpc[B]);j.accountchooser.rpc.ManageRequest.METHOD="manage";j.accountchooser.rpc.AboutRequest=function(b,c){j.accountchooser[F].notEmpty(b,Y);this.method_=j.accountchooser.rpc.AboutRequest.METHOD;this.params_={clientConfig:c};this.id_=b};j.accountchooser.rpc.AboutRequest.inheritsFrom(j.accountchooser.rpc[B]);
j.accountchooser.rpc.AboutRequest.METHOD="about";j.accountchooser.rpc.QueryRequest=function(b,c,d,e){j.accountchooser[F].notEmpty(b,Y);j.accountchooser[F].notEmpty(c,ib);d&&(d=j.accountchooser.util.sanitizeAccount(d));this.method_=j.accountchooser.rpc.QueryRequest.METHOD;this.params_={query:c,account:d,clientConfig:e};this.id_=b};j.accountchooser.rpc.QueryRequest.inheritsFrom(j.accountchooser.rpc[B]);j.accountchooser.rpc.QueryRequest.METHOD=ib;
j.accountchooser.rpc.Queries={CDS_DISABLED:"cdsDisabled",CDS_EMPTY:"cdsEmpty",ACCOUNT_EXIST:"accountExist"};
j.accountchooser.rpc.parseRpcObject=function(b){var c=g;if(b){try{var d=JSON.parse(b)}catch(e){return j.accountchooser.util.log(ta),c}!d||d.jsonrpc!=Q?j.accountchooser.util.log(ra):!d.id&&!d.method?j.accountchooser.util.log(sa):d.method?(b=d.method[N](),b==j.accountchooser.rpc.RequestAckNotification.METHOD[N]()?d.params&&d.params[m]?c=new j.accountchooser.rpc.RequestAckNotification(d.params[m]):j.accountchooser.util.log(qa):b==j.accountchooser.rpc.CdsReadyNotification.METHOD[N]()?c=new j.accountchooser.rpc.CdsReadyNotification:
b==j.accountchooser.rpc.EmptyResponseNotification.METHOD[N]()?c=new j.accountchooser.rpc.EmptyResponseNotification:j.accountchooser.util.log(ua)):c=new j.accountchooser.rpc.Response(d.id,d.result,d.error)}return c};j.accountchooser.rpc.services_={};j.accountchooser.rpc.register=function(b,c){j.accountchooser[F].notEmpty(b,mb);j.accountchooser[F].notNull(c,Ua);j.accountchooser.rpc.services_[b]=c};
j.accountchooser.rpc.call=function(b,c,d){j.accountchooser[F].notEmpty(b,qb);c=c.toString();j.accountchooser.util.log(Ga+c);b.postMessage(c,d||ca)};j.accountchooser.rpc.init_=function(b){j[E]?j[E](Za,b,i):j[u]?j[u](db,b):j[J][u]?j[J][u](db,b):j.accountchooser.util.log(Fa)};j.accountchooser.rpc.client_={popupMode:i,popupWindow:g,domain:j[y].host,cdsDomain:g,iframe:g,iframeLoaded:i,cdsReady:i,queue:[]};j.accountchooser.rpc.setPopupMode=function(b){j.accountchooser.rpc.client_.popupMode=b};
j.accountchooser.rpc.getPopupMode=function(){return j.accountchooser.rpc.client_.popupMode};j.accountchooser.rpc.setPopupWindow=function(b){j.accountchooser.rpc.client_.popupWindow=b};j.accountchooser.rpc.getPopupWindow=function(){return j.accountchooser.rpc.client_.popupWindow};j.accountchooser.rpc.getCurrentDomain_=function(){return j.accountchooser.rpc.client_[D]};
j.accountchooser.rpc.process_=function(b){j.accountchooser.util.log(Ea+b.data+aa+b.origin);if(b.origin!==j.accountchooser.rpc.client_.cdsDomain)j.accountchooser.util.log(pa+b.origin);else{var c=j.accountchooser.rpc.parseRpcObject(b.data);c?j.accountchooser.rpc.fireResponseEvent(c):j.accountchooser.util.log(Ia+b.data)}};
j.accountchooser.rpc.sendRpcInQueue_=function(b){var c=j.accountchooser.rpc.client_.queue;if(c&&c[G]){for(var d=0;d<c[G];d++)j.accountchooser.rpc[L](b,c[d]);j.accountchooser.rpc.client_.queue=[]}};
j.accountchooser.rpc.initIFrame_=function(b){if(!j.accountchooser.rpc.client_.iframe){var c=k.createElement(Wa);c[t](pb,gb);c[t](Y,Na);k[K].appendChild(c);j.accountchooser.rpc.client_.iframe=c;j[E]?c[E](Ya,j.accountchooser.rpc.iframeOnLoad_,i):j[u]?c[u](cb,j.accountchooser.rpc.iframeOnLoad_,i):j.accountchooser.util.log(oa);c[t](nb,b)}};
j.accountchooser.rpc.iframeOnLoad_=function(){j.accountchooser.rpc.client_.iframeLoaded=f;if(!j.accountchooser.rpc.client_.popupMode){var b=j.accountchooser.rpc.client_.iframe.contentWindow;j.accountchooser.rpc[L](b,new j.accountchooser.rpc.ClientReadyNotification);j.accountchooser.rpc.sendRpcInQueue_(b)}};j.accountchooser.rpc.onCdsReady_=function(){j.accountchooser.rpc.client_.cdsReady=f;j.accountchooser.rpc.client_.popupMode&&j.accountchooser.rpc.sendRpcInQueue_(j.accountchooser.rpc.client_.popupWindow)};
j.accountchooser.rpc.initClient=function(b){b.popupMode&&j.accountchooser.rpc.setPopupMode(b.popupMode);b.popupWindow&&j.accountchooser.rpc.setPopupWindow(b.popupWindow);j.accountchooser.rpc.init_(j.accountchooser.rpc.process_);j.accountchooser.rpc.client_.popupMode||j.accountchooser.rpc.initIFrame_(b.iframeUrl);j.accountchooser.rpc.client_.cdsDomain=b.cdsDomain};
j.accountchooser.rpc.callCds=function(b){if(j.accountchooser.rpc.client_.popupMode)if(j.accountchooser.rpc.client_.cdsReady)c=j.accountchooser.rpc.client_.popupWindow,j.accountchooser.rpc[L](c,b);else j.accountchooser.rpc.client_.queue[A](b);else if(j.accountchooser.rpc.client_.iframeLoaded){var c=j.accountchooser.rpc.client_.iframe.contentWindow;j.accountchooser.rpc[L](c,b)}else j.accountchooser.rpc.client_.queue[A](b)};j.accountchooser.rpc.EVENT_ACK="ack";j.accountchooser.rpc.EVENT_DONE="done";
j.accountchooser.rpc.EVENT_CDS_READY="cdsReady";j.accountchooser.rpc.EVENT_EMPTY_RESPONSE="emptyResponse";j.accountchooser.rpc.ALL_EVENTS=[j.accountchooser.rpc.EVENT_ACK,j.accountchooser.rpc.EVENT_DONE,j.accountchooser.rpc.EVENT_CDS_READY,j.accountchooser.rpc.EVENT_EMPTY_RESPONSE];j.accountchooser.rpc.DONE_AND_ACK=[j.accountchooser.rpc.EVENT_ACK,j.accountchooser.rpc.EVENT_DONE];j.accountchooser.rpc.listeners_=[];
j.accountchooser.rpc.makeEventArray_=function(b){var c=[];if(b)if(j.accountchooser.util[z](b))for(var d=0;d<b[G];d++)-1<j.accountchooser.util[C](b[d],j.accountchooser.rpc.ALL_EVENTS)?c[A](b[d]):j.accountchooser.util.log(Ha+b[d]);else-1<j.accountchooser.util[C](b,j.accountchooser.rpc.ALL_EVENTS)?c[A](b):j.accountchooser.util.log(Ha+b);else c=j.accountchooser.rpc.ALL_EVENTS.slice(0);return c};
j.accountchooser.rpc.getEventType_=function(b){var c=g;b instanceof j.accountchooser.rpc.RequestAckNotification?c=j.accountchooser.rpc.EVENT_ACK:b instanceof j.accountchooser.rpc.CdsReadyNotification?c=j.accountchooser.rpc.EVENT_CDS_READY:b instanceof j.accountchooser.rpc.Response?c=j.accountchooser.rpc.EVENT_DONE:b instanceof j.accountchooser.rpc.EmptyResponseNotification&&(c=j.accountchooser.rpc.EVENT_EMPTY_RESPONSE);return c};
j.accountchooser.rpc.addResponseListener=function(b,c,d,e){c=j.accountchooser.rpc.makeEventArray_(c);j.accountchooser.rpc.listeners_[A]({listener:b,events:c,oneTime:!!d,service:e})};j.accountchooser.rpc.removeResponseListener=function(b){for(var c=0;c<j.accountchooser.rpc.listeners_[G];)j.accountchooser.rpc.listeners_[c].listener==b?j.accountchooser.rpc.listeners_.splice(c,1):c++};j.accountchooser.rpc.clearResponseListeners=function(){j.accountchooser.rpc.listeners_=[]};
j.accountchooser.rpc.fireResponseEvent=function(b){var c=j.accountchooser.rpc.getEventType_(b);if(c)for(var d=0;d<j.accountchooser.rpc.listeners_[G];){var e=j.accountchooser.rpc.listeners_[d];if(0>j.accountchooser.util[C](c,e.events))d++;else{if(e.service)if(b instanceof j.accountchooser.rpc.RequestAckNotification&&b.params_[m]!=e.service){d++;continue}else if(b instanceof j.accountchooser.rpc.Response&&b.id_!=e.service){d++;continue}e.listener(b);e.oneTime?j.accountchooser.rpc.listeners_.splice(d,
1):d++}}};
j.accountchooser.CdsClient=function(b){j.accountchooser.util.checkSNISupported();j.accountchooser[F].notEmpty(b,Ra);b=j.accountchooser.util[q](f,{},{cdsServer:{domain:j.accountchooser.rpc.DEFAULT_CDS_DOMAIN,iframe:j.accountchooser.rpc.DEFAULT_CDS_IFRAME_PATH,popup:j.accountchooser.rpc.DEFAULT_CDS_POPUP_PATH,redirect:j.accountchooser.rpc.DEFAULT_CDS_REDIRECT_PATH},popupWidth:j.accountchooser.rpc.DEFAULT_POPUP_WIDTH,popupHeight:j.accountchooser.rpc.DEFAULT_POPUP_HEIGHT,clientCallbackUrl:j[y].href},b);
var c=b.cdsServer;c.iframe=c[D]+c.iframe;c.popup=c[D]+c.popup;c.redirect=c[D]+c.redirect;this.config_=b;this.cdsOptions_={clientCallbackUrl:this.config_.clientCallbackUrl,positiveCallbackUrl:this.config_.positiveCallbackUrl,negativeCallbackUrl:this.config_.negativeCallbackUrl,keepPopup:!!this.config_.keepPopup,showAll:!!this.config_.showAll,idpFilter:this.config_.idpFilter,language:this.config_.language,ui:this.config_.ui}};
j.accountchooser.CdsClient.init=function(b){b=new j.accountchooser.CdsClient(b);b.init();return b};Z=j.accountchooser.CdsClient[H];
Z.init=function(){this.config_.popupMode&&j.accountchooser.rpc[r](j.accountchooser.rpc.onCdsReady_,j.accountchooser.rpc.EVENT_CDS_READY);this.registerListeners_(this.config_.oneTimeCallbacks,f);this.registerListeners_(this.config_.callbacks,i);j.accountchooser.rpc.initClient({popupMode:this.config_.popupMode,popupWindow:this.config_.popupWindow,iframeUrl:this.config_.cdsServer.iframe,cdsDomain:this.config_.cdsServer[D]});return this};Z.setPopupWindow=function(b){j.accountchooser.rpc.setPopupWindow(b)};
Z.getPopupWindow=function(){return j.accountchooser.rpc.getPopupWindow()};Z.closePopupWindow=function(){this.config_.popupWindow=g;j.accountchooser.rpc.client_.popupWindow&&(j.accountchooser.rpc.client_.popupWindow.closed||j.accountchooser.rpc.client_.popupWindow.close(),j.accountchooser.rpc.client_.popupWindow=g)};
Z.changePopupModeTo=function(b){if(this.config_.popupMode!=b){var c=this.config_.popupMode;this.config_.popupMode=b;c?j.accountchooser.rpc.removeResponseListener(j.accountchooser.rpc.onCdsReady_):j.accountchooser.rpc[r](j.accountchooser.rpc.onCdsReady_,j.accountchooser.rpc.EVENT_CDS_READY);j.accountchooser.rpc.setPopupMode(b)}};
Z.registerListeners_=function(b,c){if(b)for(var d in b){var e=b[d];if(e){j.accountchooser[F].notEmptyFunction(e,(c?bb:Qa)+d);var h;h=d==j.accountchooser.rpc.EMPTY_RESPONSE_CALLBACK?j.accountchooser.rpc.EVENT_EMPTY_RESPONSE:j.accountchooser.rpc.EVENT_DONE;e=this.wrapCallback_(e);j.accountchooser.rpc[r](e,h,c,d)}}};
Z.openPopupWindow_=function(){j.accountchooser.rpc.client_.cdsReady=i;var b=j.accountchooser.rpc.client_.popupWindow;!b||b.closed?b=j.accountchooser.util.showPopup(this.config_.popupWidth,this.config_.popupHeight,this.config_.cdsServer.popup):(b.focus(),b.window[y].href=this.config_.cdsServer.popup);return j.accountchooser.rpc.client_.popupWindow=b};
Z.prepareCall_=function(b){if(this.config_.popupMode)this.openPopupWindow_();else{var c=this.config_.cdsServer.redirect,c=c+(ba+j.accountchooser.rpc.getCurrentDomain_());j.accountchooser.rpc[r](function(){j[y].href=c},j.accountchooser.rpc.EVENT_ACK,f,b)}};Z.wrapCallback_=function(b){return function(c){c instanceof j.accountchooser.rpc.Response?b(c.result_,c.getError()):b()}};
Z.createLookAheadQueryCallback_=function(b,c,d){var e=this;return function(h,n){var p=typeof c===Ta?c(h):!!c;!n&&p?j.accountchooser.rpc.fireResponseEvent(new j.accountchooser.rpc.Response(b.id_,d)):e.callCds_(b)}};Z.callCds_=function(b){this.prepareCall_(b.id_);j.accountchooser.rpc.callCds(b)};Z.store=function(b,c){j.accountchooser[F].notEmpty(b,Oa);var d=c?j.accountchooser.util[q](i,{},this.cdsOptions_,c):this.cdsOptions_,d=new j.accountchooser.rpc.StoreRequest(ob,b,d);this.callCds_(d)};
Z.select=function(b,c){var d=c?j.accountchooser.util[q](i,{},this.cdsOptions_,c):this.cdsOptions_,d=new j.accountchooser.rpc.SelectRequest(lb,b,d);this.callCds_(d)};Z.update=function(b,c){j.accountchooser[F].notEmpty(b,Ma);var d=c?j.accountchooser.util[q](i,{},this.cdsOptions_,c):this.cdsOptions_,d=new j.accountchooser.rpc.UpdateRequest(sb,b,d);this.callCds_(d)};
Z.query_=function(b,c,d,e){j.accountchooser[F].notEmptyFunction(d,Pa);if(this.config_.popupMode)d(a,{code:-32601,message:wa,data:Da});else{var h=jb+b+X+(new Date).getTime();d=this.wrapCallback_(d);j.accountchooser.rpc[r](d,j.accountchooser.rpc.EVENT_DONE,f,h);e=e?j.accountchooser.util[q](i,{},this.cdsOptions_,e):this.cdsOptions_;b=new j.accountchooser.rpc.QueryRequest(h,b,c,e);j.accountchooser.rpc.callCds(b)}};
Z.checkCdsDisabled=function(b){this.query_(j.accountchooser.rpc.Queries.CDS_DISABLED,g,b)};Z.checkCdsEmpty=function(b){this.query_(j.accountchooser.rpc.Queries.CDS_EMPTY,g,b)};Z.checkAccountExist=function(b,c){this.query_(j.accountchooser.rpc.Queries.ACCOUNT_EXIST,b,c)};})()
