/* Copyright 2012 Google Inc. All Rights Reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

(function(){var a=void 0,f=!0,g=null,j=!1,k=window,m=document;function p(b,c){return b.toJSON=c}
var q="requestId",r="extend",s="addResponseListener",t="match",u="setAttribute",v="attachEvent",w="documentElement",x="toJSON",y="split",z="location",A="isArray",B="push",C="Request",D="indexOf",E="domain",F="addEventListener",G="param",H="length",I="prototype",J="clientWidth",K="document",L="body",M="call",N="clientHeight",O="toLowerCase",P="",aa=" from ",ba="#",Q="&",ca="*",da=",height=",ea=",left=",fa=",status=1,location=1,resizable=yes,menubar=no,toolbar=no,titlebar=no,channelmode=no,directories=no,fullscreen=no",ga=
",top=",ha=".",ia="10.1",ja="10.5.6",R="2.0",S="3.0",ka="4.0",la="4.7",T="6.0",U="7.0",ma="8.0",na="=",V="?",oa="Android",pa="Failed to add iframe onload event.",qa="Ingore message from unrecognized domain: ",ra="Invalid JSON-RPC notification: no 'params.requestId' field found.",sa="Invalid JSON-RPC object: 'jsonrpc' field should be '2.0'.",ta="Invalid JSON-RPC object: no 'id' or 'method' field found.",ua="Invalid JSON-RPC object: not a JSON object.",va="Invalid JSON-RPC response: invalid 'id' field.",
wa="MSIE",xa="Method not found",ya="Opera Mini",za="Opera Mobi",Aa="Parameter %%param%% cannot be an empty array.",W="Parameter %%param%% cannot be empty.",Ba="Parameter %%param%% cannot be null.",Ca="Parameter %%param%% is not a function.",Da="Parameter %%param%% is not an array.",Ea="Query request is not supported in popup mode.",Fa="Received message: ",Ga="Register handler for postMessage failed.",Ha="Send message: ",Ia="Unrecognized event type: ",Ja="Unrecognized rpc received: ",Ka="[object Array]",
La="[object Function]",X="_",Ma="about:blank",Na="account",Oa="accountchooser-iframe",Pa="accounts",Qa="callback",Ra="callbacks.",Sa="config",Ta="form",Ua="function",Va="handler",Wa="hidden",Y="id",Xa="iframe",Ya="input",Za="load",$a="message",ab="name",bb="object",cb="oneTimeCallbacks.",db="onload",eb="onmessage",fb="parentClass",gb="popin-box",hb="position: absolute; width: 1px; height: 1px; left: -9999px;",ib="post",jb="query",kb="query_",lb="requestId",mb="select",nb="serviceName",ob="src",pb=
"store",qb="style",rb="targetWindow",sb="type",tb="update",ub="value",vb="version",wb="width=",Z;k.accountchooser=k.accountchooser||{};k.cds=k.accountchooser;k.accountchooser.util=k.accountchooser.util||{};k.accountchooser.util.log=function(b){try{k.console&&k.console.log&&k.console.log(b)}catch(c){}};k.accountchooser.util.uuidCounter_=(new Date).getTime();k.accountchooser.util.generateUuid=function(b){return b&&b.uuid?b.uuid:++k.accountchooser.util.uuidCounter_};
k.accountchooser.util.createForm_=function(b,c,d){if(!b)throw"The targetUrl cannot be null.";var e=k[K].createElement(Ta);e.method=ib;e.action=b;if(c)for(var h in c)b=k[K].createElement(Ya),b[u](sb,Wa),b[u](ab,h),c[h]===g||c[h]===a?b[u](ub,P):b[u](ub,c[h]),e.appendChild(b);d&&(e.target=d);k[K][L].appendChild(e);return e};k.accountchooser.util.postTo=function(b,c,d){b=k.accountchooser.util.createForm_(b,c,d);b.submit();k[K][L].removeChild(b)};
k.accountchooser.util.parseUrlParams=function(b){var c={};b=b.slice(b[D](V)+1)[y](Q);for(var d=0;d<b[H];d++){var e=b[d][y](na);c[e[0]]=2==e[H]?decodeURIComponent(e[1]):a}return c};k.accountchooser.util.formRedirect=function(b,c){var d=b.substring(0,b[D](V)),e=k.accountchooser.util.parseUrlParams(b);k.accountchooser.util.postTo(d,e,c)};k.accountchooser.util.isBrowserSupported=function(){var b=999;-1!=navigator.appVersion[D](wa)&&(b=parseFloat(navigator.appVersion[y](wa)[1]));return 7<b};
k.accountchooser.util.makeUrl=function(b,c){var d=[],e;for(e in c)d[B](c[e]?e+na+c[e]:e);return b+V+d.join(Q)};k.accountchooser.util.isArray=function(b){return"undefined"!==typeof jQuery?jQuery[A](b):Object[I].toString[M](b)===Ka};k.accountchooser.util.isFunction=function(b){return"undefined"!==typeof jQuery?jQuery.isFunction(b):Object[I].toString[M](b)===La};
k.accountchooser.util.indexOf=function(b,c){if(c){if("undefined"!==typeof jQuery)return jQuery.inArray(b,c);if(c[D])return c[D](b);for(var d=c[H],e=0;e<d;e++)if(e in c&&c[e]===b)return e}return-1};k.accountchooser.util.windowWidth=function(b){if("undefined"!==typeof jQuery)return jQuery(b).width();var c=0;b.innerWidth?c=b.innerWidth:b[K]&&b[K][w]&&b[K][w][J]?c=b[K][w][J]:b[K]&&(b[K][L]&&b[K][L][J])&&(c=b[K][L][J]);return c};
k.accountchooser.util.windowHeight=function(b){if("undefined"!==typeof jQuery)return jQuery(b).height();var c=0;b.innerHeight?c=b.innerHeight:b[K]&&b[K][w]&&b[K][w][N]?c=b[K][w][N]:b[K]&&(b[K][L]&&b[K][L][N])&&(c=b[K][L][N]);return c};k.accountchooser.util.trim=function(b){return"undefined"!==typeof jQuery?jQuery.trim(b):b==g?P:String[I].trim?String[I].trim[M](b):b.replace(/^[\s\xa0]+/,P).replace(/[\s\xa0]+$/,P)};
k.accountchooser.util.extend=function(b,c,d){if(3>arguments[H])return c||{};if("undefined"!==typeof jQuery){var e=Array[I].slice[M](arguments,b?0:1);return jQuery[r].apply(jQuery,e)}if(typeof c!==bb||c==g)c={};for(var e=2,h=arguments[H];e<h;e++){var l=arguments[e];if(l!=g)for(var n in l)l[n]===a||c===l[n]||(b&&typeof l[n]==bb?(k.accountchooser.util[A](l[n])&&!k.accountchooser.util[A](c[n])&&(c[n]=[]),c[n]=k.accountchooser.util[r](f,c[n],l[n])):c[n]=l[n])}return c};k.accountchooser.param={};
k.accountchooser[G].notNull=function(b,c){(b===a||b===g)&&k.accountchooser[G].throwError_(Ba,c)};k.accountchooser[G].notEmpty=function(b,c){b||k.accountchooser[G].throwError_(W,c)};k.accountchooser[G].notEmptyArray=function(b,c){b||k.accountchooser[G].throwError_(W,c);k.accountchooser.util[A](b)||k.accountchooser[G].throwError_(Da,c);b[H]||k.accountchooser[G].throwError_(Aa,c)};
k.accountchooser[G].notEmptyFunction=function(b,c){b||k.accountchooser[G].throwError_(W,c);k.accountchooser.util.isFunction(b)||k.accountchooser[G].throwError_(Ca,c)};k.accountchooser[G].throwError_=function(b,c){try{console&&console.trace&&console.trace()}catch(d){}throw b.replace(/\%\%param\%\%/g,c?" '"+c+"'":P);};Function[I].inheritsFrom=function(b){k.accountchooser[G].notEmptyFunction(b,fb);this.prototype=new b;this[I].constructor=this;this[I].parentClass=b[I]};
k.accountchooser.util.DEFAULT_POPUP_NAME="OpenIdPopup";k.accountchooser.util.showPopup=function(b,c,d,e){var h=(k.accountchooser.util.windowHeight(k)-c)/2,l=(k.accountchooser.util.windowWidth(k)-b)/2;e=e||k.accountchooser.util.DEFAULT_POPUP_NAME;if(b=k.open(d||Ma,e,wb+b+da+c+ea+(0<l?l:0)+ga+(0<h?h:0)+fa))!m.getElementById(gb)&&k.accountchooser.util.showDarkScreen&&k.accountchooser.util.showDarkScreen(b),k.accountchooser.util.popup_=b,k.accountchooser.util.popupName_=e,b.focus();return b};
k.accountchooser.util.REGEX_MSIE_UA_=/MSIE ([\d.]+).*Windows NT ([\d.]+)/;k.accountchooser.util.REGEX_FIREFOX_UA_=/Firefox\/([\d.]+)/;k.accountchooser.util.REGEX_OPERA_UA_=/Opera[ \/]([\d.]+)(.*Version\/([\d.]+))?/;k.accountchooser.util.REGEX_CHROME_UA_=/Chrome\/([\d.]+)/;k.accountchooser.util.REGEX_SAFARI_UA_=/((Windows NT ([\d.]+))|(Mac OS X ([\d_]+))).*Version\/([\d.]+).*Safari/;k.accountchooser.util.REGEX_ANDROID_UA_=/Android ([\d.]+).*Safari/;k.accountchooser.util.REGEX_MOBILE_SAFARI_UA_=/OS ([\d_]+) like Mac OS X.*Mobile.*Safari/;
k.accountchooser.util.REGEX_KONQUEROR_UA_=/Konqueror\/([\d.]+)/;k.accountchooser.util.REGEX_MOBILE_MSIE_UA_=/MSIE ([\d.]+).*Windows Phone OS ([\d.]+)/;k.accountchooser.util.Version=function(b,c){k.accountchooser[G].notEmpty(b,vb);this.version_=b;this.components_=b[y](c||ha);for(var d=0;d<this.components_[H];++d)this.components_[d]=parseInt(this.components_[d])};
k.accountchooser.util.Version[I].compare=function(b){b instanceof k.accountchooser.util.Version||(b=new k.accountchooser.util.Version(b));for(var c=Math.max(this.components_[H],b.components_[H]),d=0;d<c;++d){var e=this.components_[d],h=b.components_[d];if(e!==a&&h!==a&&e!==h)return e-h;if(e===a)return-1;if(h===a)return 1}return 0};k.accountchooser.util.Version[I].ge=function(b){return 0<=this.compare(b)};
k.accountchooser.util.isSNISupported=function(b){var c=b||k.navigator&&k.navigator.userAgent,d;if(c){if(d=c[t](k.accountchooser.util.REGEX_OPERA_UA_))return b=new k.accountchooser.util.Version(d[3]||d[1]),0<=c[D](ya)?j:0<=c[D](za)?0<=c[D](oa)&&b.ge(ia):b.ge(ma);if(d=c[t](k.accountchooser.util.REGEX_FIREFOX_UA_))return b=new k.accountchooser.util.Version(d[1]),b.ge(R);if(d=c[t](k.accountchooser.util.REGEX_CHROME_UA_))return b=new k.accountchooser.util.Version(d[1]),b.ge(T);if(d=c[t](k.accountchooser.util.REGEX_SAFARI_UA_))return b=
new k.accountchooser.util.Version(d[6]),c=d[3]&&new k.accountchooser.util.Version(d[3]),d=d[5]&&new k.accountchooser.util.Version(d[5],X),(!(!c||!c.ge(T))||!(!d||!d.ge(ja)))&&b.ge(S);if(d=c[t](k.accountchooser.util.REGEX_ANDROID_UA_))return b=new k.accountchooser.util.Version(d[1]),b.ge(S);if(d=c[t](k.accountchooser.util.REGEX_MOBILE_SAFARI_UA_))return(new k.accountchooser.util.Version(d[1],X)).ge(ka);if(d=c[t](k.accountchooser.util.REGEX_KONQUEROR_UA_))return b=new k.accountchooser.util.Version(d[1]),
b.ge(la);if(d=c[t](k.accountchooser.util.REGEX_MOBILE_MSIE_UA_))return b=new k.accountchooser.util.Version(d[1]),c=new k.accountchooser.util.Version(d[2]),b.ge(U)&&c.ge(U);if(d=c[t](k.accountchooser.util.REGEX_MSIE_UA_))return b=new k.accountchooser.util.Version(d[1]),c=new k.accountchooser.util.Version(d[2]),b.ge(U)&&c.ge(T)}return j};k.accountchooser.util.SNI_NOT_SUPPORT_ERROR={error:"SNI is not supported."};
k.accountchooser.util.checkSNISupported=function(b){if(!k.accountchooser.util.isSNISupported(b))throw k.accountchooser.util.SNI_NOT_SUPPORT_ERROR;};k.accountchooser.util.AccountPropertyKey={EMAIL:"email",DISPLAY_NAME:"displayName",PHOTO_URL:"photoUrl",PROVIDER_ID:"providerId"};
k.accountchooser.util.sanitizeAccount=function(b,c,d){var e={},h=k.accountchooser.util.AccountPropertyKey,l;for(l in b){var n=b[l];switch(l){case h.EMAIL:case h.DISPLAY_NAME:case h.PHOTO_URL:case h.PROVIDER_ID:(n=c?c(l,n):n)&&(e[l]=n);break;default:if(!d)throw'Unrecognized key "'+l+'" for account';}}if(!e[h.EMAIL])throw"No valid email field for the account";return e};
k.accountchooser.util.sanitizeAccounts=function(b,c,d){for(var e=[],h=0,l=b[H];h<l;h++){var n=k.accountchooser.util.sanitizeAccount(b[h],c,d);e[B](n)}return e};k.accountchooser.util.accountSanitizer=function(b,c){if(b==k.accountchooser.util.AccountPropertyKey.PHOTO_URL){if(/https?:\/\//i.test(c))return c}else return html.sanitizeWithPolicy(c,function(){})};k.accountchooser.rpc=k.accountchooser.rpc||{};k.accountchooser.rpc.RpcObject=function(){};
k.accountchooser.rpc.RpcObject[I].setTimestamp=function(b){this.timestamp_=b||(new Date).getTime()};p(k.accountchooser.rpc.RpcObject[I],function(){var b={jsonrpc:R};this.timestamp_!=g&&(b.timestamp=this.timestamp_);return b});k.accountchooser.rpc.RpcObject[I].toString=function(){return JSON.stringify(this[x]())};k.accountchooser.rpc.AbstractRequest=function(b,c){this.method_=b;this.params_=c};k.accountchooser.rpc.AbstractRequest.inheritsFrom(k.accountchooser.rpc.RpcObject);Z=k.accountchooser.rpc.AbstractRequest[I];
Z.setMethod=function(b){this.method_=b};Z.getMethod=function(){return this.method_};Z.setParameters=function(b){this.params_=b};Z.getParameters=function(){return this.params_};p(Z,function(){var b=k.accountchooser.rpc.RpcObject[I][x][M](this);this.method_!=g&&(b.method=this.method_);this.params_!=g&&(b.params=this.params_);return b});k.accountchooser.rpc.Notification=function(b,c){this.method_=b;this.params_=c};k.accountchooser.rpc.Notification.inheritsFrom(k.accountchooser.rpc.AbstractRequest);
k.accountchooser.rpc.Request=function(b,c,d){this.method_=b;this.params_=c;this.id_=d};k.accountchooser.rpc[C].inheritsFrom(k.accountchooser.rpc.AbstractRequest);k.accountchooser.rpc[C][I].setId=function(b){this.id_=b};k.accountchooser.rpc[C][I].getId=function(){return this.id_};p(k.accountchooser.rpc[C][I],function(){var b=k.accountchooser.rpc.AbstractRequest[I][x][M](this);this.id_!=g&&(b.id=this.id_);return b});
k.accountchooser.rpc.Response=function(b,c,d){k.accountchooser[G].notEmpty(b,Y);this.id_=b;this.result_=c;this.error_=d};k.accountchooser.rpc.Response.inheritsFrom(k.accountchooser.rpc.RpcObject);Z=k.accountchooser.rpc.Response[I];Z.getResult=function(){return this.result_};Z.setResult=function(b){this.result_=b};Z.getError=function(){return this.error_};Z.setError=function(b){this.error_=b};Z.setId=function(b){this.id_=b};Z.getId=function(){return this.id_};
p(Z,function(){var b=k.accountchooser.rpc.RpcObject[I][x][M](this);b.id=this.id_;this.result_!=g?b.result=this.result_:this.error_!=g&&(b.error=this.error_);return b});k.accountchooser.rpc.DEFAULT_CDS_DOMAIN="https://www.accountchooser.com";k.accountchooser.rpc.DEFAULT_CDS_IFRAME_PATH="/iframe.html";k.accountchooser.rpc.DEFAULT_CDS_POPUP_PATH="/popup.html";k.accountchooser.rpc.DEFAULT_CDS_REDIRECT_PATH="/redirect.html";k.accountchooser.rpc.DEFAULT_POPUP_WIDTH=520;
k.accountchooser.rpc.DEFAULT_POPUP_HEIGHT=550;k.accountchooser.rpc.EMPTY_RESPONSE_CALLBACK="empty";k.accountchooser.rpc.IDP_TIMEOUT=3E3;k.accountchooser.rpc.RPC_TIMEOUT=3E5;k.accountchooser.rpc.RequestAckNotification=function(b){k.accountchooser[G].notEmpty(b,lb);this.method_=k.accountchooser.rpc.RequestAckNotification.METHOD;this.params_={requestId:b}};k.accountchooser.rpc.RequestAckNotification.inheritsFrom(k.accountchooser.rpc.Notification);k.accountchooser.rpc.RequestAckNotification.METHOD="requestAckNotification";
k.accountchooser.rpc.RequestAckNotification[I].setRequestId=function(b){this.params_.requestId=b};k.accountchooser.rpc.RequestAckNotification[I].getRequestId=function(){return this.params_[q]};k.accountchooser.rpc.CdsReadyNotification=function(){this.method_=k.accountchooser.rpc.CdsReadyNotification.METHOD};k.accountchooser.rpc.CdsReadyNotification.inheritsFrom(k.accountchooser.rpc.Notification);k.accountchooser.rpc.CdsReadyNotification.METHOD="cdsReadyNotification";
k.accountchooser.rpc.ClientReadyNotification=function(){this.method_=k.accountchooser.rpc.ClientReadyNotification.METHOD};k.accountchooser.rpc.ClientReadyNotification.inheritsFrom(k.accountchooser.rpc.Notification);k.accountchooser.rpc.ClientReadyNotification.METHOD="clientReadyNotification";k.accountchooser.rpc.EmptyResponseNotification=function(){this.method_=k.accountchooser.rpc.EmptyResponseNotification.METHOD};k.accountchooser.rpc.EmptyResponseNotification.inheritsFrom(k.accountchooser.rpc.Notification);
k.accountchooser.rpc.EmptyResponseNotification.METHOD="emptyResponseNotification";k.accountchooser.rpc.StoreRequest=function(b,c,d){k.accountchooser[G].notEmpty(b,Y);k.accountchooser[G].notEmptyArray(c,Pa);c&&(c=k.accountchooser.util.sanitizeAccounts(c));this.method_=k.accountchooser.rpc.StoreRequest.METHOD;this.params_={accounts:c,clientConfig:d};this.id_=b};k.accountchooser.rpc.StoreRequest.inheritsFrom(k.accountchooser.rpc[C]);k.accountchooser.rpc.StoreRequest.METHOD=pb;
k.accountchooser.rpc.SelectRequest=function(b,c,d){k.accountchooser[G].notEmpty(b,Y);c&&(c=k.accountchooser.util.sanitizeAccounts(c));this.method_=k.accountchooser.rpc.SelectRequest.METHOD;this.params_={localAccounts:c,clientConfig:d};this.id_=b};k.accountchooser.rpc.SelectRequest.inheritsFrom(k.accountchooser.rpc[C]);k.accountchooser.rpc.SelectRequest.METHOD=mb;
k.accountchooser.rpc.UpdateRequest=function(b,c,d){k.accountchooser[G].notEmpty(b,Y);k.accountchooser[G].notEmpty(c,Na);c&&(c=k.accountchooser.util.sanitizeAccount(c));this.method_=k.accountchooser.rpc.UpdateRequest.METHOD;this.params_={account:c,clientConfig:d};this.id_=b};k.accountchooser.rpc.UpdateRequest.inheritsFrom(k.accountchooser.rpc[C]);k.accountchooser.rpc.UpdateRequest.METHOD=tb;
k.accountchooser.rpc.ManageRequest=function(b,c){k.accountchooser[G].notEmpty(b,Y);this.method_=k.accountchooser.rpc.ManageRequest.METHOD;this.params_={clientConfig:c};this.id_=b};k.accountchooser.rpc.ManageRequest.inheritsFrom(k.accountchooser.rpc[C]);k.accountchooser.rpc.ManageRequest.METHOD="manage";k.accountchooser.rpc.AboutRequest=function(b,c){k.accountchooser[G].notEmpty(b,Y);this.method_=k.accountchooser.rpc.AboutRequest.METHOD;this.params_={clientConfig:c};this.id_=b};k.accountchooser.rpc.AboutRequest.inheritsFrom(k.accountchooser.rpc[C]);
k.accountchooser.rpc.AboutRequest.METHOD="about";k.accountchooser.rpc.QueryRequest=function(b,c,d,e){k.accountchooser[G].notEmpty(b,Y);k.accountchooser[G].notEmpty(c,jb);d&&(d=k.accountchooser.util.sanitizeAccount(d));this.method_=k.accountchooser.rpc.QueryRequest.METHOD;this.params_={query:c,account:d,clientConfig:e};this.id_=b};k.accountchooser.rpc.QueryRequest.inheritsFrom(k.accountchooser.rpc[C]);k.accountchooser.rpc.QueryRequest.METHOD=jb;
k.accountchooser.rpc.Queries={CDS_DISABLED:"cdsDisabled",CDS_EMPTY:"cdsEmpty",ACCOUNT_EXIST:"accountExist"};
k.accountchooser.rpc.parseRpcObject=function(b){var c=g;if(b){try{var d=JSON.parse(b)}catch(e){return k.accountchooser.util.log(ua),c}!d||d.jsonrpc!=R?k.accountchooser.util.log(sa):!d.id&&!d.method?k.accountchooser.util.log(ta):d.method?(b=d.method[O](),b==k.accountchooser.rpc.RequestAckNotification.METHOD[O]()?d.params&&d.params[q]?c=new k.accountchooser.rpc.RequestAckNotification(d.params[q]):k.accountchooser.util.log(ra):b==k.accountchooser.rpc.CdsReadyNotification.METHOD[O]()?c=new k.accountchooser.rpc.CdsReadyNotification:
b==k.accountchooser.rpc.EmptyResponseNotification.METHOD[O]()?c=new k.accountchooser.rpc.EmptyResponseNotification:k.accountchooser.util.log(va)):c=new k.accountchooser.rpc.Response(d.id,d.result,d.error)}return c};k.accountchooser.rpc.services_={};k.accountchooser.rpc.register=function(b,c){k.accountchooser[G].notEmpty(b,nb);k.accountchooser[G].notNull(c,Va);k.accountchooser.rpc.services_[b]=c};
k.accountchooser.rpc.call=function(b,c,d){k.accountchooser[G].notEmpty(b,rb);c=c.toString();k.accountchooser.util.log(Ha+c);b.postMessage(c,d||ca)};k.accountchooser.rpc.init_=function(b){k[F]?k[F]($a,b,j):k[v]?k[v](eb,b):k[K][v]?k[K][v](eb,b):k.accountchooser.util.log(Ga)};k.accountchooser.rpc.client_={popupMode:j,popupWindow:g,domain:k[z].host,cdsDomain:g,iframe:g,iframeLoaded:j,cdsReady:j,queue:[]};k.accountchooser.rpc.setPopupMode=function(b){k.accountchooser.rpc.client_.popupMode=b};
k.accountchooser.rpc.getPopupMode=function(){return k.accountchooser.rpc.client_.popupMode};k.accountchooser.rpc.setPopupWindow=function(b){k.accountchooser.rpc.client_.popupWindow=b};k.accountchooser.rpc.getPopupWindow=function(){return k.accountchooser.rpc.client_.popupWindow};k.accountchooser.rpc.getCurrentDomain_=function(){return k.accountchooser.rpc.client_[E]};
k.accountchooser.rpc.process_=function(b){k.accountchooser.util.log(Fa+b.data+aa+b.origin);if(b.origin!==k.accountchooser.rpc.client_.cdsDomain)k.accountchooser.util.log(qa+b.origin);else{var c=k.accountchooser.rpc.parseRpcObject(b.data);c?k.accountchooser.rpc.fireResponseEvent(c):k.accountchooser.util.log(Ja+b.data)}};
k.accountchooser.rpc.sendRpcInQueue_=function(b){var c=k.accountchooser.rpc.client_.queue;if(c&&c[H]){for(var d=0;d<c[H];d++)k.accountchooser.rpc[M](b,c[d]);k.accountchooser.rpc.client_.queue=[]}};
k.accountchooser.rpc.initIFrame_=function(b){if(!k.accountchooser.rpc.client_.iframe){var c=m.createElement(Xa);c[u](qb,hb);c[u](Y,Oa);m[L].appendChild(c);k.accountchooser.rpc.client_.iframe=c;k[F]?c[F](Za,k.accountchooser.rpc.iframeOnLoad_,j):k[v]?c[v](db,k.accountchooser.rpc.iframeOnLoad_,j):k.accountchooser.util.log(pa);c[u](ob,b)}};
k.accountchooser.rpc.iframeOnLoad_=function(){k.accountchooser.rpc.client_.iframeLoaded=f;if(!k.accountchooser.rpc.client_.popupMode){var b=k.accountchooser.rpc.client_.iframe.contentWindow;k.accountchooser.rpc[M](b,new k.accountchooser.rpc.ClientReadyNotification);k.accountchooser.rpc.sendRpcInQueue_(b)}};k.accountchooser.rpc.onCdsReady_=function(){k.accountchooser.rpc.client_.cdsReady=f;k.accountchooser.rpc.client_.popupMode&&k.accountchooser.rpc.sendRpcInQueue_(k.accountchooser.rpc.client_.popupWindow)};
k.accountchooser.rpc.initClient=function(b){b.popupMode&&k.accountchooser.rpc.setPopupMode(b.popupMode);b.popupWindow&&k.accountchooser.rpc.setPopupWindow(b.popupWindow);k.accountchooser.rpc.init_(k.accountchooser.rpc.process_);k.accountchooser.rpc.client_.popupMode||k.accountchooser.rpc.initIFrame_(b.iframeUrl);k.accountchooser.rpc.client_.cdsDomain=b.cdsDomain};
k.accountchooser.rpc.callCds=function(b){if(k.accountchooser.rpc.client_.popupMode)if(k.accountchooser.rpc.client_.cdsReady)c=k.accountchooser.rpc.client_.popupWindow,k.accountchooser.rpc[M](c,b);else k.accountchooser.rpc.client_.queue[B](b);else if(k.accountchooser.rpc.client_.iframeLoaded){var c=k.accountchooser.rpc.client_.iframe.contentWindow;k.accountchooser.rpc[M](c,b)}else k.accountchooser.rpc.client_.queue[B](b)};k.accountchooser.rpc.EVENT_ACK="ack";k.accountchooser.rpc.EVENT_DONE="done";
k.accountchooser.rpc.EVENT_CDS_READY="cdsReady";k.accountchooser.rpc.EVENT_EMPTY_RESPONSE="emptyResponse";k.accountchooser.rpc.ALL_EVENTS=[k.accountchooser.rpc.EVENT_ACK,k.accountchooser.rpc.EVENT_DONE,k.accountchooser.rpc.EVENT_CDS_READY,k.accountchooser.rpc.EVENT_EMPTY_RESPONSE];k.accountchooser.rpc.DONE_AND_ACK=[k.accountchooser.rpc.EVENT_ACK,k.accountchooser.rpc.EVENT_DONE];k.accountchooser.rpc.listeners_=[];
k.accountchooser.rpc.makeEventArray_=function(b){var c=[];if(b)if(k.accountchooser.util[A](b))for(var d=0;d<b[H];d++)-1<k.accountchooser.util[D](b[d],k.accountchooser.rpc.ALL_EVENTS)?c[B](b[d]):k.accountchooser.util.log(Ia+b[d]);else-1<k.accountchooser.util[D](b,k.accountchooser.rpc.ALL_EVENTS)?c[B](b):k.accountchooser.util.log(Ia+b);else c=k.accountchooser.rpc.ALL_EVENTS.slice(0);return c};
k.accountchooser.rpc.getEventType_=function(b){var c=g;b instanceof k.accountchooser.rpc.RequestAckNotification?c=k.accountchooser.rpc.EVENT_ACK:b instanceof k.accountchooser.rpc.CdsReadyNotification?c=k.accountchooser.rpc.EVENT_CDS_READY:b instanceof k.accountchooser.rpc.Response?c=k.accountchooser.rpc.EVENT_DONE:b instanceof k.accountchooser.rpc.EmptyResponseNotification&&(c=k.accountchooser.rpc.EVENT_EMPTY_RESPONSE);return c};
k.accountchooser.rpc.addResponseListener=function(b,c,d,e){c=k.accountchooser.rpc.makeEventArray_(c);k.accountchooser.rpc.listeners_[B]({listener:b,events:c,oneTime:!!d,service:e})};k.accountchooser.rpc.removeResponseListener=function(b){for(var c=0;c<k.accountchooser.rpc.listeners_[H];)k.accountchooser.rpc.listeners_[c].listener==b?k.accountchooser.rpc.listeners_.splice(c,1):c++};k.accountchooser.rpc.clearResponseListeners=function(){k.accountchooser.rpc.listeners_=[]};
k.accountchooser.rpc.fireResponseEvent=function(b){var c=k.accountchooser.rpc.getEventType_(b);if(c)for(var d=0;d<k.accountchooser.rpc.listeners_[H];){var e=k.accountchooser.rpc.listeners_[d];if(0>k.accountchooser.util[D](c,e.events))d++;else{if(e.service)if(b instanceof k.accountchooser.rpc.RequestAckNotification&&b.params_[q]!=e.service){d++;continue}else if(b instanceof k.accountchooser.rpc.Response&&b.id_!=e.service){d++;continue}e.listener(b);e.oneTime?k.accountchooser.rpc.listeners_.splice(d,
1):d++}}};
k.accountchooser.CdsClient=function(b){k.accountchooser.util.checkSNISupported();k.accountchooser[G].notEmpty(b,Sa);b=k.accountchooser.util[r](f,{},{cdsServer:{domain:k.accountchooser.rpc.DEFAULT_CDS_DOMAIN,iframe:k.accountchooser.rpc.DEFAULT_CDS_IFRAME_PATH,popup:k.accountchooser.rpc.DEFAULT_CDS_POPUP_PATH,redirect:k.accountchooser.rpc.DEFAULT_CDS_REDIRECT_PATH},popupWidth:k.accountchooser.rpc.DEFAULT_POPUP_WIDTH,popupHeight:k.accountchooser.rpc.DEFAULT_POPUP_HEIGHT,clientCallbackUrl:k[z].href},b);
var c=b.cdsServer;c.iframe=c[E]+c.iframe;c.popup=c[E]+c.popup;c.redirect=c[E]+c.redirect;this.config_=b;this.cdsOptions_={clientCallbackUrl:this.config_.clientCallbackUrl,positiveCallbackUrl:this.config_.positiveCallbackUrl,negativeCallbackUrl:this.config_.negativeCallbackUrl,keepPopup:!!this.config_.keepPopup,showAll:!!this.config_.showAll,idpFilter:this.config_.idpFilter,language:this.config_.language,ui:this.config_.ui}};
k.accountchooser.CdsClient.init=function(b){b=new k.accountchooser.CdsClient(b);b.init();return b};Z=k.accountchooser.CdsClient[I];
Z.init=function(){this.config_.popupMode&&k.accountchooser.rpc[s](k.accountchooser.rpc.onCdsReady_,k.accountchooser.rpc.EVENT_CDS_READY);this.registerListeners_(this.config_.oneTimeCallbacks,f);this.registerListeners_(this.config_.callbacks,j);k.accountchooser.rpc.initClient({popupMode:this.config_.popupMode,popupWindow:this.config_.popupWindow,iframeUrl:this.config_.cdsServer.iframe,cdsDomain:this.config_.cdsServer[E]});return this};Z.setPopupWindow=function(b){k.accountchooser.rpc.setPopupWindow(b)};
Z.getPopupWindow=function(){return k.accountchooser.rpc.getPopupWindow()};Z.closePopupWindow=function(){this.config_.popupWindow=g;k.accountchooser.rpc.client_.popupWindow&&(k.accountchooser.rpc.client_.popupWindow.closed||k.accountchooser.rpc.client_.popupWindow.close(),k.accountchooser.rpc.client_.popupWindow=g)};
Z.changePopupModeTo=function(b){if(this.config_.popupMode!=b){var c=this.config_.popupMode;this.config_.popupMode=b;c?k.accountchooser.rpc.removeResponseListener(k.accountchooser.rpc.onCdsReady_):k.accountchooser.rpc[s](k.accountchooser.rpc.onCdsReady_,k.accountchooser.rpc.EVENT_CDS_READY);k.accountchooser.rpc.setPopupMode(b)}};
Z.registerListeners_=function(b,c){if(b)for(var d in b){var e=b[d];if(e){k.accountchooser[G].notEmptyFunction(e,(c?cb:Ra)+d);var h;h=d==k.accountchooser.rpc.EMPTY_RESPONSE_CALLBACK?k.accountchooser.rpc.EVENT_EMPTY_RESPONSE:k.accountchooser.rpc.EVENT_DONE;e=this.wrapCallback_(e);k.accountchooser.rpc[s](e,h,c,d)}}};
Z.openPopupWindow_=function(){k.accountchooser.rpc.client_.cdsReady=j;var b=k.accountchooser.rpc.client_.popupWindow;!b||b.closed?b=k.accountchooser.util.showPopup(this.config_.popupWidth,this.config_.popupHeight,this.config_.cdsServer.popup):(b.focus(),b.window[z].href=this.config_.cdsServer.popup);return k.accountchooser.rpc.client_.popupWindow=b};
Z.prepareCall_=function(b){if(this.config_.popupMode)this.openPopupWindow_();else{var c=this.config_.cdsServer.redirect,c=c+(ba+k.accountchooser.rpc.getCurrentDomain_());k.accountchooser.rpc[s](function(){k[z].href=c},k.accountchooser.rpc.EVENT_ACK,f,b)}};Z.wrapCallback_=function(b){return function(c){c instanceof k.accountchooser.rpc.Response?b(c.result_,c.getError()):b()}};
Z.createLookAheadQueryCallback_=function(b,c,d){var e=this;return function(h,l){var n=typeof c===Ua?c(h):!!c;!l&&n?k.accountchooser.rpc.fireResponseEvent(new k.accountchooser.rpc.Response(b.id_,d)):e.callCds_(b)}};Z.callCds_=function(b){this.prepareCall_(b.id_);k.accountchooser.rpc.callCds(b)};Z.store=function(b,c){k.accountchooser[G].notEmpty(b,Pa);var d=c?k.accountchooser.util[r](j,{},this.cdsOptions_,c):this.cdsOptions_,d=new k.accountchooser.rpc.StoreRequest(pb,b,d);this.callCds_(d)};
Z.select=function(b,c){var d=c?k.accountchooser.util[r](j,{},this.cdsOptions_,c):this.cdsOptions_,d=new k.accountchooser.rpc.SelectRequest(mb,b,d);this.callCds_(d)};Z.update=function(b,c){k.accountchooser[G].notEmpty(b,Na);var d=c?k.accountchooser.util[r](j,{},this.cdsOptions_,c):this.cdsOptions_,d=new k.accountchooser.rpc.UpdateRequest(tb,b,d);this.callCds_(d)};
Z.query_=function(b,c,d,e){k.accountchooser[G].notEmptyFunction(d,Qa);if(this.config_.popupMode)d(a,{code:-32601,message:xa,data:Ea});else{var h=kb+b+X+(new Date).getTime();d=this.wrapCallback_(d);k.accountchooser.rpc[s](d,k.accountchooser.rpc.EVENT_DONE,f,h);e=e?k.accountchooser.util[r](j,{},this.cdsOptions_,e):this.cdsOptions_;b=new k.accountchooser.rpc.QueryRequest(h,b,c,e);k.accountchooser.rpc.callCds(b)}};
Z.checkCdsDisabled=function(b){this.query_(k.accountchooser.rpc.Queries.CDS_DISABLED,g,b)};Z.checkCdsEmpty=function(b){this.query_(k.accountchooser.rpc.Queries.CDS_EMPTY,g,b)};Z.checkAccountExist=function(b,c){this.query_(k.accountchooser.rpc.Queries.ACCOUNT_EXIST,b,c)};})()
