/* Copyright 2012 Google Inc. All Rights Reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

(function(){var a=void 0,f=!0,g=null,h=!1,i=window,k=document;function l(b,c){return b.toJSON=c}
var m="requestId",p="extend",q="addResponseListener",r="match",s="setAttribute",t="attachEvent",u="documentElement",v="toJSON",w="split",x="location",y="isArray",z="push",A="Request",B="indexOf",C="domain",D="param",E="addEventListener",F="length",G="prototype",H="clientWidth",I="document",J="body",K="call",L="clientHeight",M="toLowerCase",N="",aa=" from ",ba="#",O="&",ca="*",da=",height=",ea=",left=",fa=",status=1,location=1,resizable=yes,menubar=no,toolbar=no,titlebar=no,channelmode=no,directories=no,fullscreen=no",ga=
",top=",ha=".",ia="10.1",ja="10.5.6",P="2.0",Q="3.0",ka="4.0",la="4.7",R="6.0",S="7.0",ma="8.0",T="=",U="?",na="Android",oa="Failed to add iframe onload event.",pa="Ingore message from unrecognized domain: ",qa="Invalid JSON-RPC notification: no 'params.requestId' field found.",ra="Invalid JSON-RPC object: 'jsonrpc' field should be '2.0'.",sa="Invalid JSON-RPC object: no 'id' or 'method' field found.",ta="Invalid JSON-RPC object: not a JSON object.",ua="Invalid JSON-RPC response: invalid 'id' field.",
va="MSIE",wa="Method not found",xa="Opera Mini",ya="Opera Mobi",za="Parameter %%param%% cannot be an empty array.",V="Parameter %%param%% cannot be empty.",Aa="Parameter %%param%% cannot be null.",Ba="Parameter %%param%% is not a function.",Ca="Parameter %%param%% is not an array.",Da="Query request is not supported in popup mode.",Ea="Received message: ",Fa="Register handler for postMessage failed.",Ga="Send message: ",Ha="Unrecognized event type: ",Ia="Unrecognized rpc received: ",Ja="[object Array]",
Ka="[object Function]",W="_",La="about:blank",X="account",Ma="accountchooser-iframe",Na="callback",Oa="callbacks.",Pa="config",Qa="form",Ra="function",Sa="handler",Ta="hidden",Y="id",Ua="iframe",Va="input",Wa="load",Xa="message",Ya="name",Za="object",$a="oneTimeCallbacks.",ab="onload",bb="onmessage",cb="parentClass",db="popin-box",eb="position: absolute; width: 1px; height: 1px; left: -9999px;",fb="post",gb="query",hb="query_",ib="requestId",jb="select",kb="serviceName",lb="src",mb="store",nb="style",
ob="targetWindow",pb="type",qb="update",rb="value",sb="version",tb="width=",Z;i.accountchooser=i.accountchooser||{};i.cds=i.accountchooser;i.accountchooser.util=i.accountchooser.util||{};i.accountchooser.util.log=function(b){try{i.console&&i.console.log&&i.console.log(b)}catch(c){}};i.accountchooser.util.uuidCounter_=(new Date).getTime();i.accountchooser.util.generateUuid=function(b){return b&&b.uuid?b.uuid:++i.accountchooser.util.uuidCounter_};
i.accountchooser.util.createForm_=function(b,c,d){if(!b)throw"The targetUrl cannot be null.";var e=i[I].createElement(Qa);e.method=fb;e.action=b;if(c)for(var j in c)b=i[I].createElement(Va),b[s](pb,Ta),b[s](Ya,j),c[j]===g||c[j]===a?b[s](rb,N):b[s](rb,c[j]),e.appendChild(b);d&&(e.target=d);i[I][J].appendChild(e);return e};i.accountchooser.util.postTo=function(b,c,d){b=i.accountchooser.util.createForm_(b,c,d);b.submit();i[I][J].removeChild(b)};
i.accountchooser.util.parseUrlParams=function(b){for(var c={},b=b.slice(b[B](U)+1)[w](O),d=0;d<b[F];d++){var e=b[d][w](T);c[e[0]]=2==e[F]?decodeURIComponent(e[1]):a}return c};i.accountchooser.util.formRedirect=function(b,c){var d=b.substring(0,b[B](U)),e=i.accountchooser.util.parseUrlParams(b);i.accountchooser.util.postTo(d,e,c)};i.accountchooser.util.isBrowserSupported=function(){var b=999;-1!=navigator.appVersion[B](va)&&(b=parseFloat(navigator.appVersion[w](va)[1]));return 7<b};
i.accountchooser.util.makeUrl=function(b,c){var d=[],e;for(e in c)d[z](c[e]?e+T+c[e]:e);return b+U+d.join(O)};i.accountchooser.util.isArray=function(b){return"undefined"!==typeof jQuery?jQuery[y](b):Object[G].toString[K](b)===Ja};i.accountchooser.util.isFunction=function(b){return"undefined"!==typeof jQuery?jQuery.isFunction(b):Object[G].toString[K](b)===Ka};
i.accountchooser.util.indexOf=function(b,c){if(c){if("undefined"!==typeof jQuery)return jQuery.inArray(b,c);if(c[B])return c[B](b);for(var d=c[F],e=0;e<d;e++)if(e in c&&c[e]===b)return e}return-1};i.accountchooser.util.windowWidth=function(b){if("undefined"!==typeof jQuery)return jQuery(b).width();var c=0;b.innerWidth?c=b.innerWidth:b[I]&&b[I][u]&&b[I][u][H]?c=b[I][u][H]:b[I]&&(b[I][J]&&b[I][J][H])&&(c=b[I][J][H]);return c};
i.accountchooser.util.windowHeight=function(b){if("undefined"!==typeof jQuery)return jQuery(b).height();var c=0;b.innerHeight?c=b.innerHeight:b[I]&&b[I][u]&&b[I][u][L]?c=b[I][u][L]:b[I]&&(b[I][J]&&b[I][J][L])&&(c=b[I][J][L]);return c};i.accountchooser.util.trim=function(b){return"undefined"!==typeof jQuery?jQuery.trim(b):b==g?N:String[G].trim?String[G].trim[K](b):b.replace(/^[\s\xa0]+/,N).replace(/[\s\xa0]+$/,N)};
i.accountchooser.util.extend=function(b,c,d){if(3>arguments[F])return c||{};if("undefined"!==typeof jQuery){var e=Array[G].slice[K](arguments,b?0:1);return jQuery[p].apply(jQuery,e)}if(typeof c!==Za||c==g)c={};for(var e=2,j=arguments[F];e<j;e++){var n=arguments[e];if(n!=g)for(var o in n)n[o]===a||c===n[o]||(b&&typeof n[o]==Za?(i.accountchooser.util[y](n[o])&&!i.accountchooser.util[y](c[o])&&(c[o]=[]),c[o]=i.accountchooser.util[p](f,c[o],n[o])):c[o]=n[o])}return c};i.accountchooser.param={};
i.accountchooser[D].notNull=function(b,c){(b===a||b===g)&&i.accountchooser[D].throwError_(Aa,c)};i.accountchooser[D].notEmpty=function(b,c){b||i.accountchooser[D].throwError_(V,c)};i.accountchooser[D].notEmptyArray=function(b,c){b||i.accountchooser[D].throwError_(V,c);i.accountchooser.util[y](b)||i.accountchooser[D].throwError_(Ca,c);b[F]||i.accountchooser[D].throwError_(za,c)};
i.accountchooser[D].notEmptyFunction=function(b,c){b||i.accountchooser[D].throwError_(V,c);i.accountchooser.util.isFunction(b)||i.accountchooser[D].throwError_(Ba,c)};i.accountchooser[D].throwError_=function(b,c){try{console&&console.trace&&console.trace()}catch(d){}throw b.replace(/\%\%param\%\%/g,c?" '"+c+"'":N);};Function[G].inheritsFrom=function(b){i.accountchooser[D].notEmptyFunction(b,cb);this.prototype=new b;this[G].constructor=this;this[G].parentClass=b[G]};
i.accountchooser.util.DEFAULT_POPUP_NAME="OpenIdPopup";i.accountchooser.util.showPopup=function(b,c,d,e){var j=(i.accountchooser.util.windowHeight(i)-c)/2,n=(i.accountchooser.util.windowWidth(i)-b)/2,e=e||i.accountchooser.util.DEFAULT_POPUP_NAME;if(b=i.open(d||La,e,tb+b+da+c+ea+(0<n?n:0)+ga+(0<j?j:0)+fa))!k.getElementById(db)&&i.accountchooser.util.showDarkScreen&&i.accountchooser.util.showDarkScreen(b),i.accountchooser.util.popup_=b,i.accountchooser.util.popupName_=e,b.focus();return b};
i.accountchooser.util.REGEX_MSIE_UA_=/MSIE ([\d.]+).*Windows NT ([\d.]+)/;i.accountchooser.util.REGEX_FIREFOX_UA_=/Firefox\/([\d.]+)/;i.accountchooser.util.REGEX_OPERA_UA_=/Opera[ \/]([\d.]+)(.*Version\/([\d.]+))?/;i.accountchooser.util.REGEX_CHROME_UA_=/Chrome\/([\d.]+)/;i.accountchooser.util.REGEX_SAFARI_UA_=/((Windows NT ([\d.]+))|(Mac OS X ([\d_]+))).*Version\/([\d.]+).*Safari/;i.accountchooser.util.REGEX_ANDROID_UA_=/Android ([\d.]+).*Safari/;i.accountchooser.util.REGEX_MOBILE_SAFARI_UA_=/OS ([\d_]+) like Mac OS X.*Mobile.*Safari/;
i.accountchooser.util.REGEX_KONQUEROR_UA_=/Konqueror\/([\d.]+)/;i.accountchooser.util.REGEX_MOBILE_MSIE_UA_=/MSIE ([\d.]+).*Windows Phone OS ([\d.]+)/;i.accountchooser.util.Version=function(b,c){i.accountchooser[D].notEmpty(b,sb);this.version_=b;this.components_=b[w](c||ha);for(var d=0;d<this.components_[F];++d)this.components_[d]=parseInt(this.components_[d])};
i.accountchooser.util.Version[G].compare=function(b){b instanceof i.accountchooser.util.Version||(b=new i.accountchooser.util.Version(b));for(var c=Math.max(this.components_[F],b.components_[F]),d=0;d<c;++d){var e=this.components_[d],j=b.components_[d];if(e!==a&&j!==a&&e!==j)return e-j;if(e===a)return-1;if(j===a)return 1}return 0};i.accountchooser.util.Version[G].ge=function(b){return 0<=this.compare(b)};
i.accountchooser.util.isSNISupported=function(b){var c=b||i.navigator&&i.navigator.userAgent,d;if(c){if(d=c[r](i.accountchooser.util.REGEX_OPERA_UA_))return b=new i.accountchooser.util.Version(d[3]||d[1]),0<=c[B](xa)?h:0<=c[B](ya)?0<=c[B](na)&&b.ge(ia):b.ge(ma);if(d=c[r](i.accountchooser.util.REGEX_FIREFOX_UA_))return b=new i.accountchooser.util.Version(d[1]),b.ge(P);if(d=c[r](i.accountchooser.util.REGEX_CHROME_UA_))return b=new i.accountchooser.util.Version(d[1]),b.ge(R);if(d=c[r](i.accountchooser.util.REGEX_SAFARI_UA_))return b=
new i.accountchooser.util.Version(d[6]),c=d[3]&&new i.accountchooser.util.Version(d[3]),d=d[5]&&new i.accountchooser.util.Version(d[5],W),(!(!c||!c.ge(R))||!(!d||!d.ge(ja)))&&b.ge(Q);if(d=c[r](i.accountchooser.util.REGEX_ANDROID_UA_))return b=new i.accountchooser.util.Version(d[1]),b.ge(Q);if(d=c[r](i.accountchooser.util.REGEX_MOBILE_SAFARI_UA_))return(new i.accountchooser.util.Version(d[1],W)).ge(ka);if(d=c[r](i.accountchooser.util.REGEX_KONQUEROR_UA_))return b=new i.accountchooser.util.Version(d[1]),
b.ge(la);if(d=c[r](i.accountchooser.util.REGEX_MOBILE_MSIE_UA_))return b=new i.accountchooser.util.Version(d[1]),c=new i.accountchooser.util.Version(d[2]),b.ge(S)&&c.ge(S);if(d=c[r](i.accountchooser.util.REGEX_MSIE_UA_))return b=new i.accountchooser.util.Version(d[1]),c=new i.accountchooser.util.Version(d[2]),b.ge(S)&&c.ge(R)}return h};i.accountchooser.util.SNI_NOT_SUPPORT_ERROR={error:"SNI is not supported."};
i.accountchooser.util.checkSNISupported=function(b){if(!i.accountchooser.util.isSNISupported(b))throw i.accountchooser.util.SNI_NOT_SUPPORT_ERROR;};i.accountchooser.rpc=i.accountchooser.rpc||{};i.accountchooser.rpc.RpcObject=function(){};i.accountchooser.rpc.RpcObject[G].setTimestamp=function(b){this.timestamp_=b||(new Date).getTime()};l(i.accountchooser.rpc.RpcObject[G],function(){var b={jsonrpc:P};this.timestamp_!=g&&(b.timestamp=this.timestamp_);return b});
i.accountchooser.rpc.RpcObject[G].toString=function(){return JSON.stringify(this[v]())};i.accountchooser.rpc.AbstractRequest=function(b,c){this.method_=b;this.params_=c};i.accountchooser.rpc.AbstractRequest.inheritsFrom(i.accountchooser.rpc.RpcObject);Z=i.accountchooser.rpc.AbstractRequest[G];Z.setMethod=function(b){this.method_=b};Z.getMethod=function(){return this.method_};Z.setParameters=function(b){this.params_=b};Z.getParameters=function(){return this.params_};
l(Z,function(){var b=i.accountchooser.rpc.RpcObject[G][v][K](this);this.method_!=g&&(b.method=this.method_);this.params_!=g&&(b.params=this.params_);return b});i.accountchooser.rpc.Notification=function(b,c){this.method_=b;this.params_=c};i.accountchooser.rpc.Notification.inheritsFrom(i.accountchooser.rpc.AbstractRequest);i.accountchooser.rpc.Request=function(b,c,d){this.method_=b;this.params_=c;this.id_=d};i.accountchooser.rpc[A].inheritsFrom(i.accountchooser.rpc.AbstractRequest);
i.accountchooser.rpc[A][G].setId=function(b){this.id_=b};i.accountchooser.rpc[A][G].getId=function(){return this.id_};l(i.accountchooser.rpc[A][G],function(){var b=i.accountchooser.rpc.AbstractRequest[G][v][K](this);this.id_!=g&&(b.id=this.id_);return b});i.accountchooser.rpc.Response=function(b,c,d){i.accountchooser[D].notEmpty(b,Y);this.id_=b;this.result_=c;this.error_=d};i.accountchooser.rpc.Response.inheritsFrom(i.accountchooser.rpc.RpcObject);Z=i.accountchooser.rpc.Response[G];Z.getResult=function(){return this.result_};
Z.setResult=function(b){this.result_=b};Z.getError=function(){return this.error_};Z.setError=function(b){this.error_=b};Z.setId=function(b){this.id_=b};Z.getId=function(){return this.id_};l(Z,function(){var b=i.accountchooser.rpc.RpcObject[G][v][K](this);b.id=this.id_;this.result_!=g?b.result=this.result_:this.error_!=g&&(b.error=this.error_);return b});i.accountchooser.rpc.DEFAULT_CDS_DOMAIN="https://www.accountchooser.com";i.accountchooser.rpc.DEFAULT_CDS_IFRAME_PATH="/iframe.html";
i.accountchooser.rpc.DEFAULT_CDS_POPUP_PATH="/popup.html";i.accountchooser.rpc.DEFAULT_CDS_REDIRECT_PATH="/redirect.html";i.accountchooser.rpc.DEFAULT_POPUP_WIDTH=520;i.accountchooser.rpc.DEFAULT_POPUP_HEIGHT=550;i.accountchooser.rpc.EMPTY_RESPONSE_CALLBACK="empty";i.accountchooser.rpc.IDP_TIMEOUT=3E3;i.accountchooser.rpc.RPC_TIMEOUT=3E5;
i.accountchooser.rpc.RequestAckNotification=function(b){i.accountchooser[D].notEmpty(b,ib);this.method_=i.accountchooser.rpc.RequestAckNotification.METHOD;this.params_={requestId:b}};i.accountchooser.rpc.RequestAckNotification.inheritsFrom(i.accountchooser.rpc.Notification);i.accountchooser.rpc.RequestAckNotification.METHOD="requestAckNotification";i.accountchooser.rpc.RequestAckNotification[G].setRequestId=function(b){this.params_.requestId=b};
i.accountchooser.rpc.RequestAckNotification[G].getRequestId=function(){return this.params_[m]};i.accountchooser.rpc.CdsReadyNotification=function(){this.method_=i.accountchooser.rpc.CdsReadyNotification.METHOD};i.accountchooser.rpc.CdsReadyNotification.inheritsFrom(i.accountchooser.rpc.Notification);i.accountchooser.rpc.CdsReadyNotification.METHOD="cdsReadyNotification";i.accountchooser.rpc.ClientReadyNotification=function(){this.method_=i.accountchooser.rpc.ClientReadyNotification.METHOD};i.accountchooser.rpc.ClientReadyNotification.inheritsFrom(i.accountchooser.rpc.Notification);
i.accountchooser.rpc.ClientReadyNotification.METHOD="clientReadyNotification";i.accountchooser.rpc.EmptyResponseNotification=function(){this.method_=i.accountchooser.rpc.EmptyResponseNotification.METHOD};i.accountchooser.rpc.EmptyResponseNotification.inheritsFrom(i.accountchooser.rpc.Notification);i.accountchooser.rpc.EmptyResponseNotification.METHOD="emptyResponseNotification";
i.accountchooser.rpc.StoreRequest=function(b,c,d,e){i.accountchooser[D].notEmpty(b,Y);i.accountchooser[D].notEmpty(c,X);this.method_=i.accountchooser.rpc.StoreRequest.METHOD;this.params_={account:c,localAccounts:d,clientConfig:e};this.id_=b};i.accountchooser.rpc.StoreRequest.inheritsFrom(i.accountchooser.rpc[A]);i.accountchooser.rpc.StoreRequest.METHOD=mb;
i.accountchooser.rpc.SelectRequest=function(b,c,d){i.accountchooser[D].notEmpty(b,Y);this.method_=i.accountchooser.rpc.SelectRequest.METHOD;this.params_={localAccounts:c,clientConfig:d};this.id_=b};i.accountchooser.rpc.SelectRequest.inheritsFrom(i.accountchooser.rpc[A]);i.accountchooser.rpc.SelectRequest.METHOD=jb;
i.accountchooser.rpc.UpdateRequest=function(b,c,d){i.accountchooser[D].notEmpty(b,Y);i.accountchooser[D].notEmpty(c,X);this.method_=i.accountchooser.rpc.UpdateRequest.METHOD;this.params_={account:c,clientConfig:d};this.id_=b};i.accountchooser.rpc.UpdateRequest.inheritsFrom(i.accountchooser.rpc[A]);i.accountchooser.rpc.UpdateRequest.METHOD=qb;
i.accountchooser.rpc.ManageRequest=function(b,c){i.accountchooser[D].notEmpty(b,Y);this.method_=i.accountchooser.rpc.ManageRequest.METHOD;this.params_={clientConfig:c};this.id_=b};i.accountchooser.rpc.ManageRequest.inheritsFrom(i.accountchooser.rpc[A]);i.accountchooser.rpc.ManageRequest.METHOD="manage";
i.accountchooser.rpc.QueryRequest=function(b,c,d,e){i.accountchooser[D].notEmpty(b,Y);i.accountchooser[D].notEmpty(c,gb);this.method_=i.accountchooser.rpc.QueryRequest.METHOD;this.params_={query:c,account:d,clientConfig:e};this.id_=b};i.accountchooser.rpc.QueryRequest.inheritsFrom(i.accountchooser.rpc[A]);i.accountchooser.rpc.QueryRequest.METHOD=gb;i.accountchooser.rpc.Queries={CDS_DISABLED:"cdsDisabled",CDS_EMPTY:"cdsEmpty",ACCOUNT_EXIST:"accountExist"};
i.accountchooser.rpc.parseRpcObject=function(b){var c=g;if(b){try{var d=JSON.parse(b)}catch(e){return i.accountchooser.util.log(ta),c}!d||d.jsonrpc!=P?i.accountchooser.util.log(ra):!d.id&&!d.method?i.accountchooser.util.log(sa):d.method?(b=d.method[M](),b==i.accountchooser.rpc.RequestAckNotification.METHOD[M]()?d.params&&d.params[m]?c=new i.accountchooser.rpc.RequestAckNotification(d.params[m]):i.accountchooser.util.log(qa):b==i.accountchooser.rpc.CdsReadyNotification.METHOD[M]()?c=new i.accountchooser.rpc.CdsReadyNotification:
b==i.accountchooser.rpc.EmptyResponseNotification.METHOD[M]()?c=new i.accountchooser.rpc.EmptyResponseNotification:i.accountchooser.util.log(ua)):c=new i.accountchooser.rpc.Response(d.id,d.result,d.error)}return c};i.accountchooser.rpc.services_={};i.accountchooser.rpc.register=function(b,c){i.accountchooser[D].notEmpty(b,kb);i.accountchooser[D].notNull(c,Sa);i.accountchooser.rpc.services_[b]=c};
i.accountchooser.rpc.call=function(b,c,d){i.accountchooser[D].notEmpty(b,ob);c=c.toString();i.accountchooser.util.log(Ga+c);b.postMessage(c,d||ca)};i.accountchooser.rpc.init_=function(b){i[E]?i[E](Xa,b,h):i[t]?i[t](bb,b):i[I][t]?i[I][t](bb,b):i.accountchooser.util.log(Fa)};i.accountchooser.rpc.client_={popupMode:h,popupWindow:g,domain:i[x].host,cdsDomain:g,iframe:g,iframeLoaded:h,cdsReady:h,queue:[]};i.accountchooser.rpc.setPopupMode=function(b){i.accountchooser.rpc.client_.popupMode=b};
i.accountchooser.rpc.getPopupMode=function(){return i.accountchooser.rpc.client_.popupMode};i.accountchooser.rpc.setPopupWindow=function(b){i.accountchooser.rpc.client_.popupWindow=b};i.accountchooser.rpc.getPopupWindow=function(){return i.accountchooser.rpc.client_.popupWindow};i.accountchooser.rpc.getCurrentDomain_=function(){return i.accountchooser.rpc.client_[C]};
i.accountchooser.rpc.process_=function(b){i.accountchooser.util.log(Ea+b.data+aa+b.origin);if(b.origin!==i.accountchooser.rpc.client_.cdsDomain)i.accountchooser.util.log(pa+b.origin);else{var c=i.accountchooser.rpc.parseRpcObject(b.data);c?i.accountchooser.rpc.fireResponseEvent(c):i.accountchooser.util.log(Ia+b.data)}};
i.accountchooser.rpc.sendRpcInQueue_=function(b){var c=i.accountchooser.rpc.client_.queue;if(c&&c[F]){for(var d=0;d<c[F];d++)i.accountchooser.rpc[K](b,c[d]);i.accountchooser.rpc.client_.queue=[]}};
i.accountchooser.rpc.initIFrame_=function(b){if(!i.accountchooser.rpc.client_.iframe){var c=k.createElement(Ua);c[s](nb,eb);c[s](Y,Ma);k[J].appendChild(c);i.accountchooser.rpc.client_.iframe=c;i[E]?c[E](Wa,i.accountchooser.rpc.iframeOnLoad_,h):i[t]?c[t](ab,i.accountchooser.rpc.iframeOnLoad_,h):i.accountchooser.util.log(oa);c[s](lb,b)}};
i.accountchooser.rpc.iframeOnLoad_=function(){i.accountchooser.rpc.client_.iframeLoaded=f;if(!i.accountchooser.rpc.client_.popupMode){var b=i.accountchooser.rpc.client_.iframe.contentWindow;i.accountchooser.rpc[K](b,new i.accountchooser.rpc.ClientReadyNotification);i.accountchooser.rpc.sendRpcInQueue_(b)}};i.accountchooser.rpc.onCdsReady_=function(){i.accountchooser.rpc.client_.cdsReady=f;i.accountchooser.rpc.client_.popupMode&&i.accountchooser.rpc.sendRpcInQueue_(i.accountchooser.rpc.client_.popupWindow)};
i.accountchooser.rpc.initClient=function(b){b.popupMode&&i.accountchooser.rpc.setPopupMode(b.popupMode);b.popupWindow&&i.accountchooser.rpc.setPopupWindow(b.popupWindow);i.accountchooser.rpc.init_(i.accountchooser.rpc.process_);i.accountchooser.rpc.client_.popupMode||i.accountchooser.rpc.initIFrame_(b.iframeUrl);i.accountchooser.rpc.client_.cdsDomain=b.cdsDomain};
i.accountchooser.rpc.callCds=function(b){if(i.accountchooser.rpc.client_.popupMode)if(i.accountchooser.rpc.client_.cdsReady)c=i.accountchooser.rpc.client_.popupWindow,i.accountchooser.rpc[K](c,b);else i.accountchooser.rpc.client_.queue[z](b);else if(i.accountchooser.rpc.client_.iframeLoaded){var c=i.accountchooser.rpc.client_.iframe.contentWindow;i.accountchooser.rpc[K](c,b)}else i.accountchooser.rpc.client_.queue[z](b)};i.accountchooser.rpc.EVENT_ACK="ack";i.accountchooser.rpc.EVENT_DONE="done";
i.accountchooser.rpc.EVENT_CDS_READY="cdsReady";i.accountchooser.rpc.EVENT_EMPTY_RESPONSE="emptyResponse";i.accountchooser.rpc.ALL_EVENTS=[i.accountchooser.rpc.EVENT_ACK,i.accountchooser.rpc.EVENT_DONE,i.accountchooser.rpc.EVENT_CDS_READY,i.accountchooser.rpc.EVENT_EMPTY_RESPONSE];i.accountchooser.rpc.DONE_AND_ACK=[i.accountchooser.rpc.EVENT_ACK,i.accountchooser.rpc.EVENT_DONE];i.accountchooser.rpc.listeners_=[];
i.accountchooser.rpc.makeEventArray_=function(b){var c=[];if(b)if(i.accountchooser.util[y](b))for(var d=0;d<b[F];d++)-1<i.accountchooser.util[B](b[d],i.accountchooser.rpc.ALL_EVENTS)?c[z](b[d]):i.accountchooser.util.log(Ha+b[d]);else-1<i.accountchooser.util[B](b,i.accountchooser.rpc.ALL_EVENTS)?c[z](b):i.accountchooser.util.log(Ha+b);else c=i.accountchooser.rpc.ALL_EVENTS.slice(0);return c};
i.accountchooser.rpc.getEventType_=function(b){var c=g;b instanceof i.accountchooser.rpc.RequestAckNotification?c=i.accountchooser.rpc.EVENT_ACK:b instanceof i.accountchooser.rpc.CdsReadyNotification?c=i.accountchooser.rpc.EVENT_CDS_READY:b instanceof i.accountchooser.rpc.Response?c=i.accountchooser.rpc.EVENT_DONE:b instanceof i.accountchooser.rpc.EmptyResponseNotification&&(c=i.accountchooser.rpc.EVENT_EMPTY_RESPONSE);return c};
i.accountchooser.rpc.addResponseListener=function(b,c,d,e){c=i.accountchooser.rpc.makeEventArray_(c);i.accountchooser.rpc.listeners_[z]({listener:b,events:c,oneTime:!!d,service:e})};i.accountchooser.rpc.removeResponseListener=function(b){for(var c=0;c<i.accountchooser.rpc.listeners_[F];)i.accountchooser.rpc.listeners_[c].listener==b?i.accountchooser.rpc.listeners_.splice(c,1):c++};i.accountchooser.rpc.clearResponseListeners=function(){i.accountchooser.rpc.listeners_=[]};
i.accountchooser.rpc.fireResponseEvent=function(b){var c=i.accountchooser.rpc.getEventType_(b);if(c)for(var d=0;d<i.accountchooser.rpc.listeners_[F];){var e=i.accountchooser.rpc.listeners_[d];if(0>i.accountchooser.util[B](c,e.events))d++;else{if(e.service)if(b instanceof i.accountchooser.rpc.RequestAckNotification&&b.params_[m]!=e.service){d++;continue}else if(b instanceof i.accountchooser.rpc.Response&&b.id_!=e.service){d++;continue}e.listener(b);e.oneTime?i.accountchooser.rpc.listeners_.splice(d,
1):d++}}};
i.accountchooser.CdsClient=function(b){i.accountchooser.util.checkSNISupported();i.accountchooser[D].notEmpty(b,Pa);var b=i.accountchooser.util[p](f,{},i.accountchooser.CdsClient.DEFAULT_CDS_CLIENT_CONFIG_,b),c=b.cdsServer;c.iframe=c[C]+c.iframe;c.popup=c[C]+c.popup;c.redirect=c[C]+c.redirect;this.config_=b;this.cdsOptions_={clientCallbackUrl:this.config_.clientCallbackUrl,positiveCallbackUrl:this.config_.positiveCallbackUrl,negativeCallbackUrl:this.config_.negativeCallbackUrl,keepPopup:!!this.config_.keepPopup,showAll:!!this.config_.showAll,
idpFilter:this.config_.idpFilter,language:this.config_.language,ui:this.config_.ui}};i.accountchooser.CdsClient.DEFAULT_CDS_CLIENT_CONFIG_={cdsServer:{domain:i.accountchooser.rpc.DEFAULT_CDS_DOMAIN,iframe:i.accountchooser.rpc.DEFAULT_CDS_IFRAME_PATH,popup:i.accountchooser.rpc.DEFAULT_CDS_POPUP_PATH,redirect:i.accountchooser.rpc.DEFAULT_CDS_REDIRECT_PATH},popupWidth:i.accountchooser.rpc.DEFAULT_POPUP_WIDTH,popupHeight:i.accountchooser.rpc.DEFAULT_POPUP_HEIGHT,clientCallbackUrl:i[x].href};
i.accountchooser.CdsClient.init=function(b){b=new i.accountchooser.CdsClient(b);b.init();return b};Z=i.accountchooser.CdsClient[G];
Z.init=function(){this.config_.popupMode&&i.accountchooser.rpc[q](i.accountchooser.rpc.onCdsReady_,i.accountchooser.rpc.EVENT_CDS_READY);this.registerListeners_(this.config_.oneTimeCallbacks,f);this.registerListeners_(this.config_.callbacks,h);i.accountchooser.rpc.initClient({popupMode:this.config_.popupMode,popupWindow:this.config_.popupWindow,iframeUrl:this.config_.cdsServer.iframe,cdsDomain:this.config_.cdsServer[C]});return this};Z.setPopupWindow=function(b){i.accountchooser.rpc.setPopupWindow(b)};
Z.getPopupWindow=function(){return i.accountchooser.rpc.getPopupWindow()};Z.closePopupWindow=function(){this.config_.popupWindow=g;i.accountchooser.rpc.client_.popupWindow&&(i.accountchooser.rpc.client_.popupWindow.closed||i.accountchooser.rpc.client_.popupWindow.close(),i.accountchooser.rpc.client_.popupWindow=g)};
Z.changePopupModeTo=function(b){if(this.config_.popupMode!=b){var c=this.config_.popupMode;this.config_.popupMode=b;c?i.accountchooser.rpc.removeResponseListener(i.accountchooser.rpc.onCdsReady_):i.accountchooser.rpc[q](i.accountchooser.rpc.onCdsReady_,i.accountchooser.rpc.EVENT_CDS_READY);i.accountchooser.rpc.setPopupMode(b)}};
Z.registerListeners_=function(b,c){if(b)for(var d in b){var e=b[d];if(e){i.accountchooser[D].notEmptyFunction(e,(c?$a:Oa)+d);var j;j=d==i.accountchooser.rpc.EMPTY_RESPONSE_CALLBACK?i.accountchooser.rpc.EVENT_EMPTY_RESPONSE:i.accountchooser.rpc.EVENT_DONE;e=this.wrapCallback_(e);i.accountchooser.rpc[q](e,j,c,d)}}};
Z.openPopupWindow_=function(){i.accountchooser.rpc.client_.cdsReady=h;var b=i.accountchooser.rpc.client_.popupWindow;!b||b.closed?b=i.accountchooser.util.showPopup(this.config_.popupWidth,this.config_.popupHeight,this.config_.cdsServer.popup):(b.focus(),b.window[x].href=this.config_.cdsServer.popup);return i.accountchooser.rpc.client_.popupWindow=b};
Z.prepareCall_=function(b){if(this.config_.popupMode)this.openPopupWindow_();else{var c=this.config_.cdsServer.redirect,c=c+(ba+i.accountchooser.rpc.getCurrentDomain_());i.accountchooser.rpc[q](function(){i[x].href=c},i.accountchooser.rpc.EVENT_ACK,f,b)}};Z.wrapCallback_=function(b){return function(c){c instanceof i.accountchooser.rpc.Response?b(c.result_,c.getError()):b()}};
Z.createLookAheadQueryCallback_=function(b,c,d){var e=this;return function(j,n){var o=typeof c===Ra?c(j):!!c;!n&&o?i.accountchooser.rpc.fireResponseEvent(new i.accountchooser.rpc.Response(b.id_,d)):e.callCds_(b)}};Z.callCds_=function(b){this.prepareCall_(b.id_);i.accountchooser.rpc.callCds(b)};Z.store=function(b,c,d){i.accountchooser[D].notEmpty(b,X);d=d?i.accountchooser.util[p](h,{},this.cdsOptions_,d):this.cdsOptions_;b=new i.accountchooser.rpc.StoreRequest(mb,b,c,d);this.callCds_(b)};
Z.select=function(b,c){var d=c?i.accountchooser.util[p](h,{},this.cdsOptions_,c):this.cdsOptions_,d=new i.accountchooser.rpc.SelectRequest(jb,b,d);this.callCds_(d)};Z.update=function(b,c){i.accountchooser[D].notEmpty(b,X);var d=c?i.accountchooser.util[p](h,{},this.cdsOptions_,c):this.cdsOptions_,d=new i.accountchooser.rpc.UpdateRequest(qb,b,d);this.callCds_(d)};
Z.query_=function(b,c,d,e){i.accountchooser[D].notEmptyFunction(d,Na);if(this.config_.popupMode)d(a,{code:-32601,message:wa,data:Da});else{var j=hb+b+W+(new Date).getTime(),d=this.wrapCallback_(d);i.accountchooser.rpc[q](d,i.accountchooser.rpc.EVENT_DONE,f,j);e=e?i.accountchooser.util[p](h,{},this.cdsOptions_,e):this.cdsOptions_;b=new i.accountchooser.rpc.QueryRequest(j,b,c,e);i.accountchooser.rpc.callCds(b)}};
Z.checkCdsDisabled=function(b){this.query_(i.accountchooser.rpc.Queries.CDS_DISABLED,g,b)};Z.checkCdsEmpty=function(b,c){this.query_(i.accountchooser.rpc.Queries.CDS_EMPTY,g,b,c)};Z.checkAccountExist=function(b,c,d){this.query_(i.accountchooser.rpc.Queries.ACCOUNT_EXIST,b,c,d)};})()
